import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LangCode = "fr" | "en" | "ewe" | "kab" | "wo";
export type CurrencyCode = "XOF" | "USD" | "EUR" | "GBP";

interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  currency: CurrencyCode;
  setCurrency: (currency: CurrencyCode) => void;
  t: (key: string) => string;
  formatPrice: (priceXOF: number) => string;
}

const exchangeRates: Record<CurrencyCode, number> = {
  XOF: 1,
  USD: 0.0016,
  EUR: 0.0015,
  GBP: 0.0013,
};

const currencySymbols: Record<CurrencyCode, string> = {
  XOF: "FCFA",
  USD: "$",
  EUR: "€",
  GBP: "£",
};

const translations: Record<LangCode, Record<string, string>> = {
  fr: {
    // Nav
    "nav.home": "Accueil",
    "nav.marketplace": "Marketplace",
    "nav.producers": "Réseaux",
    "nav.nukuai": "NUKU AI",
    "nav.formations": "Formations",
    "nav.traceability": "Traçabilité",
    "nav.tracking": "Suivre Livraison",
    "nav.about": "À propos",
    "nav.plans": "Tarifs",
    "nav.categories": "Catégories",
    "nav.navigation": "Navigation",
    "nav.langCurrency": "Langue & Devise",
    // Auth
    "auth.login": "Connexion",
    "auth.signup": "Inscription",
    "auth.logout": "Déconnexion",
    "auth.loginSignup": "Connexion / Inscription",
    "auth.myAccount": "Mon compte",
    // Header
    "header.deliverTo": "Livraison vers:",
    "header.search": "Rechercher des produits...",
    "header.searchBtn": "Rechercher",
    "header.notifications": "Notifications",
    "header.readAll": "Tout lire",
    "header.viewAllNotif": "Voir toutes les notifications",
    "header.language": "Langue",
    "header.currency": "Devise",
    "header.deliveryLocation": "Lieu de livraison",
    "header.currentLocation": "Lieu actuel",
    "header.enterAddress": "Entrez votre adresse",
    "header.cancel": "Annuler",
    "header.save": "Enregistrer",
    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.orders": "Mes commandes",
    "dashboard.payments": "Paiements",
    "dashboard.trackOrders": "Suivre mes commandes",
    "dashboard.settings": "Paramètres",
    // Cart
    "cart.title": "Mon Panier",
    "cart.empty": "Votre panier est vide",
    "cart.emptyDesc": "Parcourez le marketplace pour trouver des produits",
    "cart.explore": "Explorer le marketplace",
    "cart.subtotal": "Sous-total",
    "cart.delivery": "Livraison",
    "cart.free": "Gratuit",
    "cart.total": "Total",
    "cart.checkout": "Commander",
    "cart.seller": "Vendeur",
    "cart.back": "Retour",
    "cart.articles": "articles",
    "cart.deliveryMethod": "Mode de livraison",
    "cart.deliveryAddress": "Adresse de livraison",
    "cart.city": "Ville",
    "cart.fullAddress": "Adresse complète",
    "cart.summary": "Récapitulatif",
    "cart.addressRequired": "Adresse requise",
    "cart.addressRequiredDesc": "Veuillez entrer votre adresse de livraison",
    "cart.orderSent": "Commande envoyée !",
    "cart.orderSentDesc": "Votre commande a été transmise aux vendeurs.",
    "cart.sellerContact": "Les vendeurs vous contacteront pour confirmer la disponibilité et finaliser le paiement",
    "cart.loginRequired": "Connexion requise",
    "cart.loginRequiredDesc": "Vous devez être connecté pour passer une commande",
    "cart.loginBtn": "Se connecter",
    // Marketplace
    "mp.searchProduct": "Rechercher un produit",
    "mp.productName": "Nom du produit...",
    "mp.allCategories": "Toutes les catégories",
    "mp.price": "Prix",
    "mp.location": "Localisation",
    "mp.bioOnly": "Bio uniquement",
    "mp.verifiedOnly": "Vérifiés uniquement",
    "mp.reset": "Réinitialiser",
    "mp.filters": "Filtres",
    "mp.advancedFilters": "Filtres avancés",
    "mp.sponsored": "Produits Sponsorisés",
    "mp.viewAll": "Voir tout",
    "mp.products": "produits",
    "mp.noProducts": "Aucun produit trouvé",
    "mp.noProductsDesc": "Essayez de modifier vos filtres",
    "mp.clear": "Effacer",
    "mp.flashDeals": "Offres Flash",
    "mp.forYou": "Sélection pour vous",
    "mp.newArrivals": "Nouveautés",
    "mp.allProducts": "Tous les produits",
    "mp.sortRecent": "Plus récents",
    "mp.sortPriceAsc": "Prix croissant",
    "mp.sortPriceDesc": "Prix décroissant",
    "mp.sortRating": "Meilleures notes",
    "mp.allRegions": "Toutes les régions",
    "mp.bio": "Bio",
    "mp.verified": "Vérifiés",
    // Product
    "product.back": "Retour",
    "product.addToCart": "Ajouter au panier",
    "product.addedToCart": "Ajouté au panier",
    "product.contactSeller": "Contacter le vendeur",
    "product.sendMessage": "Envoyer un message à",
    "product.send": "Envoyer le message",
    "product.messageSent": "Message envoyé !",
    "product.quantity": "Quantité:",
    "product.estimatedTotal": "Total estimé:",
    "product.available": "disponibles",
    "product.deliveryAvailable": "Livraison disponible",
    "product.viewProfile": "Voir profil",
    "product.notFound": "Produit non trouvé",
    "product.backToMp": "Retour au marketplace",
    "product.traceability": "Traçabilité du produit",
    "product.certified": "Certifié",
    "product.notCertified": "Non certifié",
    "product.contact": "Contacter",
    "product.add": "Ajouter",
    // NukuAI
    "ai.title": "NUKU AI",
    "ai.subtitle": "Assistant agricole intelligent 24/7",
    "ai.poweredBy": "Par NukuConnect IA",
    "ai.placeholder": "Posez votre question agricole...",
    "ai.thinking": "NUKU AI réfléchit...",
    "ai.suggested": "Questions suggérées",
    "ai.categories": "Catégories d'aide",
    "ai.cropAdvice": "Conseils de culture",
    "ai.diseaseId": "Identification maladies",
    "ai.marketPrices": "Prix du marché",
    "ai.seasonal": "Recommandations saisonnières",
    "ai.livestock": "Élevage & Bétail",
    "ai.organic": "Agriculture biologique",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Irrigation & Eau",
    // HowItWorks
    "hiw.title": "Comment ça marche",
    // About
    "about.title": "À propos",
    // Common
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.seeAll": "Voir tout",
  },
  en: {
    "nav.home": "Home",
    "nav.marketplace": "Marketplace",
    "nav.producers": "Network",
    "nav.nukuai": "NUKU AI",
    "nav.formations": "Training",
    "nav.traceability": "Traceability",
    "nav.tracking": "Track Delivery",
    "nav.about": "About",
    "nav.plans": "Plans",
    "nav.categories": "Categories",
    "nav.navigation": "Navigation",
    "nav.langCurrency": "Language & Currency",
    "auth.login": "Login",
    "auth.signup": "Sign up",
    "auth.logout": "Logout",
    "auth.loginSignup": "Login / Sign up",
    "auth.myAccount": "My account",
    "header.deliverTo": "Deliver to:",
    "header.search": "Search products...",
    "header.searchBtn": "Search",
    "header.notifications": "Notifications",
    "header.readAll": "Read all",
    "header.viewAllNotif": "View all notifications",
    "header.language": "Language",
    "header.currency": "Currency",
    "header.deliveryLocation": "Delivery location",
    "header.currentLocation": "Current location",
    "header.enterAddress": "Enter your address",
    "header.cancel": "Cancel",
    "header.save": "Save",
    "dashboard.title": "Dashboard",
    "dashboard.orders": "My orders",
    "dashboard.payments": "Payments",
    "dashboard.trackOrders": "Track my orders",
    "dashboard.settings": "Settings",
    "cart.title": "My Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptyDesc": "Browse the marketplace to find products",
    "cart.explore": "Explore marketplace",
    "cart.subtotal": "Subtotal",
    "cart.delivery": "Delivery",
    "cart.free": "Free",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "cart.seller": "Seller",
    "cart.back": "Back",
    "cart.articles": "items",
    "cart.deliveryMethod": "Delivery method",
    "cart.deliveryAddress": "Delivery address",
    "cart.city": "City",
    "cart.fullAddress": "Full address",
    "cart.summary": "Summary",
    "cart.addressRequired": "Address required",
    "cart.addressRequiredDesc": "Please enter your delivery address",
    "cart.orderSent": "Order sent!",
    "cart.orderSentDesc": "Your order has been sent to sellers.",
    "cart.sellerContact": "Sellers will contact you to confirm availability and finalize payment",
    "cart.loginRequired": "Login required",
    "cart.loginRequiredDesc": "You must be logged in to place an order",
    "cart.loginBtn": "Log in",
    "mp.searchProduct": "Search a product",
    "mp.productName": "Product name...",
    "mp.allCategories": "All categories",
    "mp.price": "Price",
    "mp.location": "Location",
    "mp.bioOnly": "Organic only",
    "mp.verifiedOnly": "Verified only",
    "mp.reset": "Reset",
    "mp.filters": "Filters",
    "mp.advancedFilters": "Advanced filters",
    "mp.sponsored": "Sponsored Products",
    "mp.viewAll": "View all",
    "mp.products": "products",
    "mp.noProducts": "No products found",
    "mp.noProductsDesc": "Try changing your filters",
    "mp.clear": "Clear",
    "mp.flashDeals": "Flash Deals",
    "mp.forYou": "Selected for you",
    "mp.newArrivals": "New Arrivals",
    "mp.allProducts": "All products",
    "mp.sortRecent": "Most recent",
    "mp.sortPriceAsc": "Price: low to high",
    "mp.sortPriceDesc": "Price: high to low",
    "mp.sortRating": "Top rated",
    "mp.allRegions": "All regions",
    "mp.bio": "Organic",
    "mp.verified": "Verified",
    "product.back": "Back",
    "product.addToCart": "Add to cart",
    "product.addedToCart": "Added to cart",
    "product.contactSeller": "Contact seller",
    "product.sendMessage": "Send a message to",
    "product.send": "Send message",
    "product.messageSent": "Message sent!",
    "product.quantity": "Quantity:",
    "product.estimatedTotal": "Estimated total:",
    "product.available": "available",
    "product.deliveryAvailable": "Delivery available",
    "product.viewProfile": "View profile",
    "product.notFound": "Product not found",
    "product.backToMp": "Back to marketplace",
    "product.traceability": "Product traceability",
    "product.certified": "Certified",
    "product.notCertified": "Not certified",
    "product.contact": "Contact",
    "product.add": "Add",
    "ai.title": "NUKU AI",
    "ai.subtitle": "Smart agricultural assistant 24/7",
    "ai.poweredBy": "By Nukuconnect Technology",
    "ai.placeholder": "Ask your agricultural question...",
    "ai.thinking": "NUKU AI is thinking...",
    "ai.suggested": "Suggested questions",
    "ai.categories": "Help categories",
    "ai.cropAdvice": "Crop advice",
    "ai.diseaseId": "Disease identification",
    "ai.marketPrices": "Market prices",
    "ai.seasonal": "Seasonal recommendations",
    "ai.livestock": "Livestock & Cattle",
    "ai.organic": "Organic farming",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Irrigation & Water",
    "hiw.title": "How it works",
    "about.title": "About",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.seeAll": "See all",
  },
  ewe: {
    "nav.home": "Aƒe",
    "nav.marketplace": "Asitsaƒe",
    "nav.producers": "Nudzralatɔwo",
    "nav.nukuai": "NUKU AI",
    "nav.formations": "Kpɔɖeŋu",
    "nav.traceability": "Nudi dzadzɛ",
    "nav.tracking": "Dze nuɖoɖo ƒe ŋkume",
    "nav.about": "Ŋuti nyawo",
    "nav.plans": "Fexexe ƒe dzesi",
    "nav.categories": "Hatsatsa",
    "nav.navigation": "Mɔɖoɖo",
    "nav.langCurrency": "Gbe kple ga",
    "auth.login": "Ge ɖe eme",
    "auth.signup": "Ŋlɔ ŋkɔ",
    "auth.logout": "Tso ɖe go",
    "auth.loginSignup": "Ge ɖe eme / Ŋlɔ ŋkɔ",
    "auth.myAccount": "Nye ŋkɔnta",
    "header.deliverTo": "Na ɖo ɖe:",
    "header.search": "Di nu aɖe...",
    "header.searchBtn": "Di",
    "header.notifications": "Nyagbɔgblɔwo",
    "header.readAll": "Xlẽ wokatã",
    "header.viewAllNotif": "Kpɔ nyagbɔgblɔ wokatã",
    "header.language": "Gbe",
    "header.currency": "Ga",
    "header.deliveryLocation": "Nuɖoɖo ƒe teƒe",
    "header.currentLocation": "Teƒe si li fifia",
    "header.enterAddress": "De wò adrese",
    "header.cancel": "Dzudzɔ",
    "header.save": "Dzra ɖi",
    "dashboard.title": "Dɔwɔƒe",
    "dashboard.orders": "Nye ɖoɖowo",
    "dashboard.payments": "Fexexe",
    "dashboard.trackOrders": "Dze nye ɖoɖo ƒe ŋkume",
    "dashboard.settings": "Ɖoɖo",
    "cart.title": "Nye agba",
    "cart.empty": "Wò agba le ƒuƒlu",
    "cart.emptyDesc": "Kpɔ asitsaƒe la dzi be nàdi nuwo",
    "cart.explore": "Kpɔ asitsaƒe",
    "cart.subtotal": "Akɔnta eve",
    "cart.delivery": "Nuɖoɖo",
    "cart.free": "Fiafia",
    "cart.total": "Katã",
    "cart.checkout": "Ɖo ɖoɖo",
    "cart.seller": "Nudzrala",
    "cart.back": "Trɔ yi",
    "cart.articles": "nuwo",
    "cart.deliveryMethod": "Nuɖoɖo ƒe mɔnu",
    "cart.deliveryAddress": "Nuɖoɖo ƒe adrese",
    "cart.city": "Du",
    "cart.fullAddress": "Adrese blibo",
    "cart.summary": "Gɔmedzese",
    "cart.addressRequired": "Adrese hiã",
    "cart.addressRequiredDesc": "Taflatse ŋlɔ wò nuɖoɖo ƒe adrese",
    "cart.orderSent": "Woɖo ɖoɖo!",
    "cart.orderSentDesc": "Woɖo wò ɖoɖo na nudzralawo.",
    "cart.sellerContact": "Nudzralawo aɖo ka ɖe wò gbɔ",
    "cart.loginRequired": "Gege ɖe eme hiã",
    "cart.loginRequiredDesc": "Ele be nàge ɖe eme hafi nàɖo ɖoɖo",
    "cart.loginBtn": "Ge ɖe eme",
    "mp.searchProduct": "Di nunu aɖe",
    "mp.productName": "Nunu ƒe ŋkɔ...",
    "mp.allCategories": "Hatsatsa wokatã",
    "mp.price": "Asixɔxɔ",
    "mp.location": "Teƒe",
    "mp.bioOnly": "Bio ko",
    "mp.verifiedOnly": "Wokpɔe ɖe edzi ko",
    "mp.reset": "Trɔ ɖe dzi",
    "mp.filters": "Titia",
    "mp.advancedFilters": "Titia si dze edzi",
    "mp.sponsored": "Nuwo si woɖo ga na",
    "mp.viewAll": "Kpɔ katã",
    "mp.products": "nuwo",
    "mp.noProducts": "Womekpɔ nu aɖeke o",
    "mp.noProductsDesc": "Tsi titia bubuwo kpɔ",
    "mp.clear": "Tutu",
    "mp.flashDeals": "Asitsatsa ŋkɔŋkɔ",
    "mp.forYou": "Wotia na wò",
    "mp.newArrivals": "Nuwo si va yeye",
    "mp.allProducts": "Nuwo katã",
    "mp.sortRecent": "Yeyewo gbã",
    "mp.sortPriceAsc": "Asixɔxɔ: ɖoɖoe va gã",
    "mp.sortPriceDesc": "Asixɔxɔ: gã va ɖoɖoe",
    "mp.sortRating": "Nyuiewo gbã",
    "mp.allRegions": "Nutome wokatã",
    "mp.bio": "Bio",
    "mp.verified": "Wokpɔe ɖe edzi",
    "product.back": "Trɔ yi",
    "product.addToCart": "De agba me",
    "product.addedToCart": "Wode agba me",
    "product.contactSeller": "Ka ɖo nudzrala",
    "product.sendMessage": "Dɔ ŋutinya na",
    "product.send": "Dɔ ŋutinya",
    "product.messageSent": "Woɖo ŋutinya!",
    "product.quantity": "Gbɔsɔsɔ:",
    "product.estimatedTotal": "Katã si wobu:",
    "product.available": "woliwo",
    "product.deliveryAvailable": "Nuɖoɖo li",
    "product.viewProfile": "Kpɔ ŋkɔnta",
    "product.notFound": "Womekpɔ nu la o",
    "product.backToMp": "Trɔ yi asitsaƒe",
    "product.traceability": "Nunu ƒe dzadzɛ",
    "product.certified": "Wodzɛe",
    "product.notCertified": "Womedzɛe o",
    "product.contact": "Ka ɖo",
    "product.add": "De eme",
    "ai.title": "NUKU AI",
    "ai.subtitle": "Agble ŋutinya na ŋkeke 24/7",
    "ai.poweredBy": "Tso Nukuconnect Technologie",
    "ai.placeholder": "Bia wò agble biabia...",
    "ai.thinking": "NUKU AI le susu ɖom...",
    "ai.suggested": "Biabiawo si wotia",
    "ai.categories": "Kpekpeɖeŋu ƒe hatsatsa",
    "ai.cropAdvice": "Agble dɔwɔwɔ ƒe aɖaŋu",
    "ai.diseaseId": "Dɔlele ƒe dzadzɛ",
    "ai.marketPrices": "Asitsaƒe asixɔxɔwo",
    "ai.seasonal": "Ɣeyiɣi ƒe aɖaŋu",
    "ai.livestock": "Lãwo",
    "ai.organic": "Bio agbledede",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Tsi kple tɔ̃me",
    "hiw.title": "Alesi ewɔna",
    "about.title": "Ŋuti nyawo",
    "common.loading": "Le dzadzram...",
    "common.error": "Vodada",
    "common.seeAll": "Kpɔ katã",
  },
  kab: {
    "nav.home": "Ɖɩsɩ",
    "nav.marketplace": "Kɩyakʊ",
    "nav.producers": "Lʊlɩyaa",
    "nav.nukuai": "NUKU AI",
    "nav.formations": "Kpɛlɩkʊ",
    "nav.traceability": "Ñɩnɩʊ",
    "nav.tracking": "Ðɔɖɔ ñɩnɩʊ",
    "nav.about": "Tɔm taa",
    "nav.plans": "Liidiye",
    "nav.categories": "Hɔɔlʊʊ",
    "nav.navigation": "Nʊmɔʊ",
    "nav.langCurrency": "Kʊnʊŋ kple liidiye",
    "auth.login": "Sʊʊ",
    "auth.signup": "Maʊ hɩɖɛ",
    "auth.logout": "Lɩɩ",
    "auth.loginSignup": "Sʊʊ / Maʊ hɩɖɛ",
    "auth.myAccount": "Ma-tɩŋ",
    "header.deliverTo": "Pɩsɩ:",
    "header.search": "Ñɩnɩ...",
    "header.searchBtn": "Ñɩnɩ",
    "header.notifications": "Tɔm kɩfam",
    "header.readAll": "Kalɩ tɩŋa",
    "header.viewAllNotif": "Na tɔm kɩfam tɩŋa",
    "header.language": "Kʊnʊŋ",
    "header.currency": "Liidiye",
    "header.deliveryLocation": "Pɩsɩʊ lone",
    "header.currentLocation": "Lone lɛɛlɛɛ",
    "header.enterAddress": "Ma wɛ adrese",
    "header.cancel": "Kizi",
    "header.save": "Ðɔkɩ",
    "dashboard.title": "Tɔm taa",
    "dashboard.orders": "Ma ɖɔɖɔ",
    "dashboard.payments": "Hɛyʊʊ",
    "dashboard.trackOrders": "Ðɔɖɔ ñɩnɩʊ",
    "dashboard.settings": "Lɩmaɣzɩ",
    "cart.title": "Ma huyuu",
    "cart.empty": "Wɛ huyuu fɛyɩ",
    "cart.emptyDesc": "Wolo kɩyakʊ taa se ñɩnɩ wondu",
    "cart.explore": "Na kɩyakʊ",
    "cart.subtotal": "Tɩŋa lɛɛ",
    "cart.delivery": "Pɩsɩʊ",
    "cart.free": "Falaa",
    "cart.total": "Tɩŋa",
    "cart.checkout": "Ðɔɖɔ",
    "cart.seller": "Pɛdɩyaa",
    "cart.back": "Pɩsɩ",
    "cart.articles": "wondu",
    "cart.deliveryMethod": "Pɩsɩʊ nʊmɔʊ",
    "cart.deliveryAddress": "Pɩsɩʊ adrese",
    "cart.city": "Tɛtʊ",
    "cart.fullAddress": "Adrese tɩŋa",
    "cart.summary": "Tɔm kpɛlɩkʊ",
    "cart.addressRequired": "Adrese tɔm",
    "cart.addressRequiredDesc": "Ma wɛ adrese",
    "cart.orderSent": "Patɩ ɖɔɖɔ!",
    "cart.orderSentDesc": "Paɖɩ wɛ ɖɔɖɔ.",
    "cart.sellerContact": "Pɛdɩyaa kaɣ-ŋ yɔɔdɩnʊʊ",
    "cart.loginRequired": "Pɩwɛɛ se sʊʊ",
    "cart.loginRequiredDesc": "Pɩwɛɛ se sʊʊ nɛ pʊcɔ ɖɔɖɔ",
    "cart.loginBtn": "Sʊʊ",
    "mp.searchProduct": "Ñɩnɩ pʊyʊ",
    "mp.productName": "Pʊyʊ hɩɖɛ...",
    "mp.allCategories": "Hɔɔlʊʊ tɩŋa",
    "mp.price": "Liidiye",
    "mp.location": "Lone",
    "mp.bioOnly": "Bio ɖeke",
    "mp.verifiedOnly": "Pawɩlɩ ɖeke",
    "mp.reset": "Pɩsɩ kiɖe",
    "mp.filters": "Titia",
    "mp.advancedFilters": "Titia kɩfasɩ",
    "mp.sponsored": "Wondu ɖɩfɛyɩ",
    "mp.viewAll": "Na tɩŋa",
    "mp.products": "wondu",
    "mp.noProducts": "Patɩlɩɣ pʊyʊ",
    "mp.noProductsDesc": "Lɛɣzɩ titia",
    "mp.clear": "Hɩzɩ",
    "mp.flashDeals": "Kɩyakʊ lɛɛ",
    "mp.forYou": "Ña-tɩŋ",
    "mp.newArrivals": "Kɩfasɩ",
    "mp.allProducts": "Wondu tɩŋa",
    "mp.sortRecent": "Kɩfasɩ",
    "mp.sortPriceAsc": "Liidiye: cikpem",
    "mp.sortPriceDesc": "Liidiye: sɔsɔm",
    "mp.sortRating": "Kɩlɩm",
    "mp.allRegions": "Egeetiye tɩŋa",
    "mp.bio": "Bio",
    "mp.verified": "Pawɩlɩ",
    "product.back": "Pɩsɩ",
    "product.addToCart": "Sɩɩ huyuu taa",
    "product.addedToCart": "Pasɩ huyuu taa",
    "product.contactSeller": "Yɔɔdɩnɩ pɛdɩyaa",
    "product.sendMessage": "Tɩyɩ tɔm",
    "product.send": "Tɩyɩ tɔm",
    "product.messageSent": "Patɩyɩ tɔm!",
    "product.quantity": "Ɖɔɖɔ:",
    "product.estimatedTotal": "Tɩŋa:",
    "product.available": "wɛɛ",
    "product.deliveryAvailable": "Pɩsɩʊ wɛɛ",
    "product.viewProfile": "Na tɔm",
    "product.notFound": "Patɩlɩɣ pʊyʊ",
    "product.backToMp": "Pɩsɩ kɩyakʊ",
    "product.traceability": "Pʊyʊ ñɩnɩʊ",
    "product.certified": "Pawɩlɩ",
    "product.notCertified": "Patɩwɩlɩ",
    "product.contact": "Yɔɔdɩ",
    "product.add": "Sɩɩ",
    "ai.title": "NUKU AI",
    "ai.subtitle": "Hayɩm sɩnɩyʊ 24/7",
    "ai.poweredBy": "Nukuconnect Technologie",
    "ai.placeholder": "Pɔzɩ wɛ tɔm...",
    "ai.thinking": "NUKU AI maɣzɩɣ...",
    "ai.suggested": "Tɔm ndʊ pɔzɩ",
    "ai.categories": "Sɩnʊʊ hɔɔlʊʊ",
    "ai.cropAdvice": "Hayɩm lɔŋ",
    "ai.diseaseId": "Kʊdɔŋ ñɩnɩʊ",
    "ai.marketPrices": "Kɩyakʊ liidiye",
    "ai.seasonal": "Alɩwaatʊ lɔŋ",
    "ai.livestock": "Kpɩna",
    "ai.organic": "Bio hayɩm",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Lɩm",
    "hiw.title": "Ɛzɩma pɩlakɩ",
    "about.title": "Tɔm taa",
    "common.loading": "Ðɩɖaŋ...",
    "common.error": "Pɩtɛkɛdɩ",
    "common.seeAll": "Na tɩŋa",
  },
  wo: {
    "nav.home": "Kër",
    "nav.marketplace": "Marse",
    "nav.producers": "Yënguway yi",
    "nav.nukuai": "NUKU AI",
    "nav.formations": "Jàng",
    "nav.traceability": "Wërusit",
    "nav.tracking": "Toppoo yóbbu",
    "nav.about": "Ci xam-xam",
    "nav.plans": "Wàll",
    "nav.categories": "Xeet",
    "nav.navigation": "Yoon",
    "nav.langCurrency": "Làkk ak xaalis",
    "auth.login": "Dugg",
    "auth.signup": "Bindu",
    "auth.logout": "Génne",
    "auth.loginSignup": "Dugg / Bindu",
    "auth.myAccount": "Sama kont",
    "header.deliverTo": "Yóbbu ci:",
    "header.search": "Wut...",
    "header.searchBtn": "Wut",
    "header.notifications": "Xëbar yi",
    "header.readAll": "Jàng lépp",
    "header.viewAllNotif": "Xool xëbar yépp",
    "header.language": "Làkk",
    "header.currency": "Xaalis",
    "header.deliveryLocation": "Bërëb yóbbu",
    "header.currentLocation": "Bërëb bi léegi",
    "header.enterAddress": "Dugal sa adres",
    "header.cancel": "Bàyyi",
    "header.save": "Denc",
    "dashboard.title": "Tablo",
    "dashboard.orders": "Sama commande yi",
    "dashboard.payments": "Fay",
    "dashboard.trackOrders": "Toppoo sama commande",
    "dashboard.settings": "Parameetar",
    "cart.title": "Sama panier",
    "cart.empty": "Sa panier amul dara",
    "cart.emptyDesc": "Xoolal marse bi ngir wut jën",
    "cart.explore": "Xool marse bi",
    "cart.subtotal": "Bokk",
    "cart.delivery": "Yóbbu",
    "cart.free": "Fay-fayul",
    "cart.total": "Tollu",
    "cart.checkout": "Commande",
    "cart.seller": "Jëndëkaat",
    "cart.back": "Dellu",
    "cart.articles": "yenn",
    "cart.deliveryMethod": "Yoon wu yóbbu",
    "cart.deliveryAddress": "Adres bu yóbbu",
    "cart.city": "Dëkk",
    "cart.fullAddress": "Adres bu mat",
    "cart.summary": "Tektal",
    "cart.addressRequired": "Adres laaj na",
    "cart.addressRequiredDesc": "Dugalal sa adres bu yóbbu",
    "cart.orderSent": "Commande gi yónnee na!",
    "cart.orderSentDesc": "Sa commande gi yónnee na ci jëndëkaat yi.",
    "cart.sellerContact": "Jëndëkaat yi dinañu la woo",
    "cart.loginRequired": "Wànte dugg",
    "cart.loginRequiredDesc": "Wànte dugg ngir def commande",
    "cart.loginBtn": "Dugg",
    "mp.searchProduct": "Wut jën",
    "mp.productName": "Tur jën...",
    "mp.allCategories": "Xeet yépp",
    "mp.price": "Njëg",
    "mp.location": "Bërëb",
    "mp.bioOnly": "Bio rekk",
    "mp.verifiedOnly": "Yu wërul rekk",
    "mp.reset": "Dellu",
    "mp.filters": "Sàcc",
    "mp.advancedFilters": "Sàcc bu yëg",
    "mp.sponsored": "Jën yu sponsor",
    "mp.viewAll": "Xool lépp",
    "mp.products": "jën",
    "mp.noProducts": "Amul jën",
    "mp.noProductsDesc": "Jéemël weccil sàcc",
    "mp.clear": "Sopp",
    "mp.flashDeals": "Offre gaaw",
    "mp.forYou": "Ngir yow",
    "mp.newArrivals": "Yu bees",
    "mp.allProducts": "Jën yépp",
    "mp.sortRecent": "Yu mujj",
    "mp.sortPriceAsc": "Njëg: ndaw ba mag",
    "mp.sortPriceDesc": "Njëg: mag ba ndaw",
    "mp.sortRating": "Yu gëna baax",
    "mp.allRegions": "Bërëb yépp",
    "mp.bio": "Bio",
    "mp.verified": "Wërul",
    "product.back": "Dellu",
    "product.addToCart": "Dugal ci panier",
    "product.addedToCart": "Dugal na ci panier",
    "product.contactSeller": "Jokkoo ak jëndëkaat",
    "product.sendMessage": "Yónne bataaxal ci",
    "product.send": "Yónne",
    "product.messageSent": "Bataaxal bi yónnee na!",
    "product.quantity": "Yàgg:",
    "product.estimatedTotal": "Tollu:",
    "product.available": "am nañu",
    "product.deliveryAvailable": "Yóbbu am na",
    "product.viewProfile": "Xool profil",
    "product.notFound": "Gisul jën",
    "product.backToMp": "Dellu marse",
    "product.traceability": "Wërusit bu jën",
    "product.certified": "Certificat",
    "product.notCertified": "Amul certificat",
    "product.contact": "Jokkoo",
    "product.add": "Dugal",
    "ai.title": "NUKU AI",
    "ai.subtitle": "Ndimbal bu tool ci agrokultur 24/7",
    "ai.poweredBy": "Nukuconnect Technologie",
    "ai.placeholder": "Laajal sa laaj ci tool...",
    "ai.thinking": "NUKU AI di xalaat...",
    "ai.suggested": "Laaj yu ñu tànn",
    "ai.categories": "Xeet ndimbal",
    "ai.cropAdvice": "Digal ci tool",
    "ai.diseaseId": "Feebar ñibbi",
    "ai.marketPrices": "Njëg ci marse",
    "ai.seasonal": "Digal ci weer",
    "ai.livestock": "Mala",
    "ai.organic": "Tool bio",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Ndox",
    "hiw.title": "Nan la doxe",
    "about.title": "Ci xam-xam",
    "common.loading": "Ngi yéeg...",
    "common.error": "Njuumte",
    "common.seeAll": "Xool lépp",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<LangCode>(() => {
    return (localStorage.getItem("nukuconnect-lang") as LangCode) || "fr";
  });
  const [currency, setCurrency] = useState<CurrencyCode>(() => {
    return (localStorage.getItem("nukuconnect-currency") as CurrencyCode) || "XOF";
  });

  useEffect(() => {
    localStorage.setItem("nukuconnect-lang", lang);
  }, [lang]);

  useEffect(() => {
    localStorage.setItem("nukuconnect-currency", currency);
  }, [currency]);

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations.fr[key] || key;
  };

  const formatPrice = (priceXOF: number): string => {
    const converted = priceXOF * exchangeRates[currency];
    const symbol = currencySymbols[currency];
    if (currency === "XOF") {
      return `${new Intl.NumberFormat("fr-FR").format(Math.round(converted))} ${symbol}`;
    }
    return `${symbol}${new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(converted)}`;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, currency, setCurrency, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
