import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LangCode = "fr" | "en" | "ewe" | "kab" | "wo";
export type CurrencyCode = "XOF" | "USD" | "EUR" | "GBP";

interface LanguageContextType {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  currency: CurrencyCode;
  setCurrency: (currency: CurrencyCode) => void;
  t: (key: string) => string;
  formatPrice: (priceXOF: number) => string;
}

const exchangeRates: Record<CurrencyCode, number> = {
  XOF: 1,
  USD: 0.0016,
  EUR: 0.0015,
  GBP: 0.0013,
};

const currencySymbols: Record<CurrencyCode, string> = {
  XOF: "FCFA",
  USD: "$",
  EUR: "€",
  GBP: "£",
};

const translations: Record<LangCode, Record<string, string>> = {
  fr: {
    // Nav
    "nav.home": "Accueil",
    "nav.marketplace": "Marketplace",
    "nav.producers": "Réseaux",
    "nav.nukuai": "NUKUCONNECT IA",
    "nav.formations": "Formations",
    "nav.traceability": "Traçabilité",
    "nav.tracking": "Suivre la commande",
    "nav.about": "À propos",
    "nav.plans": "Tarifs",
    "nav.categories": "Catégories",
    "nav.navigation": "Navigation",
    "nav.langCurrency": "Langue & Devise",
    "nav.contact": "Contact",
    "nav.help": "Centre d'aide",
    // Auth
    "auth.login": "Connexion",
    "auth.signup": "Inscription",
    "auth.logout": "Déconnexion",
    "auth.loginSignup": "Connexion / Inscription",
    "auth.myAccount": "Mon compte",
    // Header
    "header.deliverTo": "Livraison vers:",
    "header.search": "Rechercher des produits...",
    "header.searchBtn": "Rechercher",
    "header.notifications": "Notifications",
    "header.readAll": "Tout lire",
    "header.viewAllNotif": "Voir toutes les notifications",
    "header.language": "Langue",
    "header.currency": "Devise",
    "header.deliveryLocation": "Lieu de livraison",
    "header.currentLocation": "Lieu actuel",
    "header.enterAddress": "Entrez votre adresse",
    "header.cancel": "Annuler",
    "header.save": "Enregistrer",
    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.orders": "Mes commandes",
    "dashboard.payments": "Paiements",
    "dashboard.trackOrders": "Suivre mes commandes",
    "dashboard.settings": "Paramètres",
    // Cart
    "cart.title": "Mon Panier",
    "cart.empty": "Votre panier est vide",
    "cart.emptyDesc": "Parcourez le marketplace pour trouver des produits",
    "cart.explore": "Explorer le marketplace",
    "cart.subtotal": "Sous-total",
    "cart.delivery": "Livraison",
    "cart.free": "Gratuit",
    "cart.total": "Total",
    "cart.checkout": "Commander",
    "cart.seller": "Vendeur",
    "cart.back": "Retour",
    "cart.articles": "articles",
    "cart.deliveryMethod": "Mode de livraison",
    "cart.deliveryAddress": "Adresse de livraison",
    "cart.city": "Ville",
    "cart.fullAddress": "Adresse complète",
    "cart.summary": "Récapitulatif",
    "cart.addressRequired": "Adresse requise",
    "cart.addressRequiredDesc": "Veuillez entrer votre adresse de livraison",
    "cart.orderSent": "Commande envoyée !",
    "cart.orderSentDesc": "Votre commande a été transmise aux vendeurs.",
    "cart.sellerContact": "Les vendeurs vous contacteront pour confirmer la disponibilité et finaliser le paiement",
    "cart.loginRequired": "Connexion requise",
    "cart.loginRequiredDesc": "Vous devez être connecté pour passer une commande",
    "cart.loginBtn": "Se connecter",
    // Marketplace
    "mp.searchProduct": "Rechercher un produit",
    "mp.productName": "Nom du produit...",
    "mp.allCategories": "Toutes les catégories",
    "mp.price": "Prix",
    "mp.location": "Localisation",
    "mp.bioOnly": "Bio uniquement",
    "mp.verifiedOnly": "Vérifiés uniquement",
    "mp.reset": "Réinitialiser",
    "mp.filters": "Filtres",
    "mp.advancedFilters": "Filtres avancés",
    "mp.sponsored": "Produits Sponsorisés",
    "mp.viewAll": "Voir tout",
    "mp.products": "produits",
    "mp.noProducts": "Aucun produit trouvé",
    "mp.noProductsDesc": "Essayez de modifier vos filtres",
    "mp.clear": "Effacer",
    "mp.flashDeals": "Offres Flash",
    "mp.forYou": "Populaires",
    "mp.newArrivals": "Nouveautés",
    "mp.allProducts": "Tous les produits",
    "mp.sortRecent": "Plus récents",
    "mp.sortPriceAsc": "Prix croissant",
    "mp.sortPriceDesc": "Prix décroissant",
    "mp.sortRating": "Meilleures notes",
    "mp.allRegions": "Toutes les régions",
    "mp.bio": "Bio",
    "mp.verified": "Vérifiés",
    "mp.productsForSale": "Produits en vente",
    "mp.purchaseRequests": "Demandes d'achat",
    "mp.allPurchaseRequests": "Toutes les demandes d'achat",
    "mp.searchDemand": "Rechercher une demande...",
    "mp.allCategoriesFilter": "Toutes catégories",
    "mp.recentPublications": "Publications récentes",
    "mp.seeAll": "Tout voir →",
    "mp.activeSuppliers": "Fournisseurs vérifiés",
    "mp.seeAllSuppliers": "Voir tous →",
    // Product
    "product.back": "Retour",
    "product.addToCart": "Ajouter au panier",
    "product.addedToCart": "Ajouté au panier",
    "product.contactSeller": "Contacter le vendeur",
    "product.sendMessage": "Envoyer un message à",
    "product.send": "Envoyer le message",
    "product.messageSent": "Message envoyé !",
    "product.quantity": "Quantité:",
    "product.estimatedTotal": "Total estimé:",
    "product.available": "disponibles",
    "product.deliveryAvailable": "Livraison disponible",
    "product.viewProfile": "Voir profil",
    "product.notFound": "Produit non trouvé",
    "product.backToMp": "Retour au marketplace",
    "product.traceability": "Traçabilité du produit",
    "product.certified": "Certifié",
    "product.notCertified": "Non certifié",
    "product.contact": "Contacter",
    "product.add": "Ajouter",
    // NukuAI
    "ai.title": "NUKUCONNECT IA",
    "ai.subtitle": "Assistant agricole intelligent 24/7",
    "ai.poweredBy": "Par NukuConnect IA",
    "ai.placeholder": "Posez votre question agricole...",
    "ai.thinking": "NUKUCONNECT IA réfléchit...",
    "ai.suggested": "Questions suggérées",
    "ai.categories": "Catégories d'aide",
    "ai.cropAdvice": "Conseils de culture",
    "ai.diseaseId": "Identification maladies",
    "ai.marketPrices": "Prix du marché",
    "ai.seasonal": "Recommandations saisonnières",
    "ai.livestock": "Élevage & Bétail",
    "ai.organic": "Agriculture biologique",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Irrigation & Eau",
    // HowItWorks
    "hiw.title": "Comment ça marche",
    // About
    "about.title": "À propos",
    // Common
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.seeAll": "Voir tout",
    // Homepage Hero
    "hero.badge": "Propulsé par l'Intelligence Artificielle",
    "hero.title1": "Connectez votre",
    "hero.title2": "production agricole",
    "hero.title3": "au monde entier",
    "hero.desc": "NUKUCONNECT révolutionne le commerce agricole en Afrique. Vendez vos produits, trouvez des acheteurs fiables et bénéficiez de l'IA pour optimiser vos cultures.",
    "hero.cta": "Commencer maintenant",
    "hero.demo": "Voir la démo",
    "hero.stat1": "Producteurs",
    "hero.stat2": "Achats réalisés",
    "hero.stat3": "Transactions",
    // Solutions
    "sol.delivery": "Livraison rapide & traçable",
    "sol.deliveryDesc": "Recevez vos produits agricoles certifiés directement chez vous avec suivi en temps réel et garantie de traçabilité complète.",
    "sol.deliveryCta": "Commander maintenant",
    "sol.markets": "Marchés locaux & internationaux",
    "sol.marketsDesc": "Accédez à un réseau de producteurs et d'acheteurs à travers l'Afrique de l'Ouest. Vendez et achetez en toute sécurité.",
    "sol.marketsCta": "Explorer le marché",
    "sol.connect": "Mise en relation pro",
    "sol.connectDesc": "Trouvez des producteurs, fournisseurs, experts et partenaires qualifiés pour développer votre activité agricole.",
    "sol.connectCta": "Devenir partenaire",
    "sol.training": "Formations spécialisées",
    "sol.trainingDesc": "Accédez à des programmes de formation en aquaculture, agriculture et agrobusiness pour booster vos compétences.",
    "sol.trainingCta": "Voir les formations",
    "sol.quickAccess": "Accès rapide",
    "sol.nukuAI": "Nuku IA",
    "sol.dashboard": "Tableau de bord",
    "sol.verifiedProducts": "Produits vérifiés",
    "home.solutionsBadge": "Solutions NUKUCONNECT",
    "home.solutionsTitleBefore": "Des solutions innovantes au service de",
    "home.solutionsTitleHighlight": "votre croissance",
    "home.solutionsDesc": "Une plateforme complète qui connecte, forme et dynamise l'agriculture et l'aquaculture en Afrique de l'Ouest et au-delà.",
    "home.popularProducts": "Produits populaires",
    "home.new": "NOUVEAU",
    "home.topCategories": "Top Catégories",
    "home.productSingular": "produit",
    "home.productPlural": "produits",
    "home.featuresBadge": "Fonctionnalités",
    "home.featuresTitleBefore": "Tout pour",
    "home.featuresTitleHighlight": "réussir",
    "home.featuresDesc": "Technologie et agriculture pour transformer votre activité.",
    "home.featureMarketplace": "Marketplace Agricole",
    "home.featureMarketplaceDesc": "Publiez et achetez des produits agricoles avec facilité.",
    "home.featureAssistant": "NUKUCONNECT IA - Assistant 24/7",
    "home.featureAssistantDesc": "Chatbot IA qui répond à vos questions agricoles.",
    "home.featureRecommendations": "Recommandations IA",
    "home.featureRecommendationsDesc": "Suggestions basées sur votre localisation et préférences.",
    "home.featureTraining": "Formations Agricoles",
    "home.featureTrainingDesc": "Cours en ligne et certifications pour vos techniques.",
    "home.featureTraceability": "Traçabilité Complète",
    "home.featureTraceabilityDesc": "Suivez vos produits avec QR codes et historique.",
    "home.featureNetwork": "Réseau de Confiance",
    "home.featureNetworkDesc": "Notation et avis pour des transactions sécurisées.",
    "home.users": "Utilisateurs",
    "home.secure": "Sécurisé",
    "home.hiwBadge": "Comment ça marche ?",
    "home.hiwTitleBefore": "Achetez en",
    "home.hiwTitleHighlight": "4 étapes simples",
    "home.hiwDesc": "De la création de compte à la livraison, découvrez comment NUKUCONNECT simplifie vos achats agricoles.",
    "home.step1Title": "Créez votre compte",
    "home.step1Desc": "Choisissez votre type de compte : Producteur, Acheteur, Fournisseur, Livreur ou Apprenant. Inscription rapide et gratuite.",
    "home.step1Link": "S'inscrire",
    "home.step2Title": "Trouvez vos produits & offres",
    "home.step2Desc": "Parcourez le marketplace, découvrez les produits agricoles locaux et consultez les offres d'achat des acheteurs.",
    "home.step2Link": "Explorer",
    "home.step3Title": "Passez commande",
    "home.step3Desc": "Contactez le producteur, négociez et achetez en toute sécurité.",
    "home.step3Link": "Acheter",
    "home.step4Title": "Livraison à domicile",
    "home.step4Desc": "Sélectionnez un livreur disponible près de vous, suivez votre commande en temps réel et recevez vos produits frais.",
    "home.step4Link": "Suivre commande",
    "home.aiMeet": "Rencontrez",
    "home.aiDesc": "Votre assistant agricole intelligent disponible 24/7. Posez vos questions sur les cultures, l'élevage, les maladies des plantes et recevez des conseils personnalisés instantanément.",
    "home.aiFeatureAdvice": "Conseils personnalisés 24/7",
    "home.aiFeatureDisease": "Diagnostic des maladies",
    "home.aiFeatureInstant": "Réponses instantanées",
    "home.aiFeatureLang": "Français & langues locales",
    "home.aiTry": "Essayer NUKUCONNECT IA",
    "home.aiOnline": "En ligne",
    "home.aiPlaceholder": "Posez votre question...",
    "home.aiMsgAssistant1": "Bonjour ! Je suis NUKUCONNECT IA, votre assistant agricole. Comment puis-je vous aider aujourd'hui ?",
    "home.aiMsgUser": "Comment améliorer le rendement de mes tomates ?",
    "home.aiMsgAssistant2": "Pour améliorer vos tomates :\n\n🌱 Sol riche en compost\n💧 Arrosage régulier le matin\n☀️ 6-8h de soleil direct\n\nVoulez-vous plus de détails ?",
    "home.ctaTitleBefore": "Prêt à transformer votre",
    "home.ctaTitleHighlight": "activité agricole",
    "home.ctaDesc": "Rejoignez des milliers de producteurs et acheteurs qui font confiance à NUKUCONNECT pour développer leur activité.",
    "home.ctaCreate": "Créer mon compte gratuit",
    "home.ctaContact": "Contacter notre équipe",
    "home.partnersTrust": "Ils nous font confiance",
    "home.demandsTitle": "Demandes d'achat",
    "home.demandsSubtitle": "Les acheteurs cherchent — répondez directement",
    "home.purchaseBadge": "ACHAT",
    "home.buyer": "Acheteur",
    "home.demandNeed": "Besoin d'achat de",
    "home.moreDemands": "Voir plus de demandes",
    "home.verifiedSuppliers": "Fournisseurs vérifiés",
    "home.farmTitleBefore": "Achetez directement chez",
    "home.farmTitleHighlight": "les producteurs",
    "home.farmTitleAfter": "sans intermédiaire",
    "home.farmDesc": "Connectez-vous aux fournisseurs vérifiés et recevez vos produits agricoles directement depuis le lieu de production. Plus de fraîcheur, des prix justes, une traçabilité totale.",
    "home.verified100": "100% vérifiés",
    "home.verified100Desc": "Identité & exploitation contrôlées",
    "home.originGuaranteed": "Origine garantie",
    "home.originGuaranteedDesc": "Du champ à votre porte",
    "home.nukuDelivery": "Livraison Nuku",
    "home.nukuDeliveryDesc": "Flotte interne suivie en direct",
    "home.buyFromProducers": "Acheter chez les producteurs",
    "home.viewSuppliers": "Voir les fournisseurs",
    "home.recentPublications": "Publications récentes",
    "home.helpTitle": "Besoin d'aide ?",
    "home.helpDesc": "Discutez avec notre Assistant IA pour trouver ce qu'il vous faut.",
    "home.chatNow": "Discuter maintenant",
    "home.whatSearch": "Que recherchez-vous ?",
    "home.whatSearchDesc": "Décrivez votre question ou ce que vous recherchez. Notre IA NukuConnect vous répondra immédiatement.",
    "home.helpPlaceholder": "Ex: Quel engrais pour le maïs ?",
    "home.sendToAI": "Envoyer à l'IA",
    "home.sellTitle": "Vendez vos produits facilement",
    "home.sellDesc": "Touchez plus d'acheteurs partout en Afrique.",
    "home.startSelling": "Commencer à vendre",
    "home.trustNetworkRealtime": "Réseau de confiance · temps réel",
    "home.networkTitle": "Producteurs & Fournisseurs Nukuconnect",
    "home.viewNetwork": "Voir le réseau",
    "home.member": "Membre",
    "home.verifiedMember": "Membre vérifié",
    "home.aiAssistant": "Assistant Agricole",
    "home.aiFloatingText": "Posez vos questions sur l'agriculture, les cultures, l'élevage ou les maladies des plantes.",
    "home.startConversation": "Démarrer une conversation",
    // Network / Producers
    "net.title": "Notre réseau professionnel",
    "net.subtitle": "Suivez les fournisseurs et acheteurs pour recevoir leurs nouvelles offres et demandes en temps réel.",
    "net.badge": "Réseau NukuConnect",
    "net.searchSupplier": "Rechercher un fournisseur...",
    "net.searchBuyer": "Rechercher un acheteur...",
    "net.suppliers": "Fournisseurs",
    "net.buyers": "Acheteurs",
    "net.mostRecent": "Plus récents",
    "net.bestRated": "Mieux notés",
    "net.mostProducts": "Plus de produits",
    "net.allCountries": "Tous les pays",
    "net.follow": "Suivre",
    "net.following": "Abonné",
    "net.products": "produit",
    "net.productsPlural": "produits",
    "net.subscriber": "abonné",
    "net.subscribersPlural": "abonnés",
    "net.buyer": "Acheteur",
    "net.verified": "Vérifié",
    "net.noSupplier": "Aucun fournisseur trouvé",
    "net.noBuyer": "Aucun acheteur trouvé",
    "net.modifyFilters": "Modifiez vos filtres de recherche.",
    "net.subscribed": "Abonné !",
    "net.unsubscribed": "Désabonné",
    "net.subscribeNotif": "Vous recevrez les notifications de",
    "net.unsubscribeNotif": "Vous ne suivez plus",
    // Footer
    "footer.platform": "Plateforme",
    "footer.resources": "Ressources",
    "footer.company": "Entreprise",
    "footer.contact": "Contact",
    "footer.terms": "Conditions d'utilisation",
    "footer.privacy": "Politique de confidentialité",
    "footer.legal": "Mentions légales",
    "footer.rights": "Tous droits réservés.",
    "footer.desc": "La marketplace agricole intelligente qui connecte producteurs et acheteurs.",
    "footer.downloadApp": "Téléchargez l'application",
    "footer.downloadDesc": "Accédez à NUKUCONNECT partout, tout le temps.",
    // KYC (supplier)
    "kyc.businessName": "Nom entreprise / activité",
    "kyc.businessNamePh": "Ex: Ferme Kokoe",
    "kyc.businessType": "Type d'activité",
    "kyc.businessType.individual": "Individuel",
    "kyc.businessType.cooperative": "Coopérative",
    "kyc.businessType.enterprise": "Entreprise",
    "kyc.idType": "Type de pièce d'identité",
    "kyc.idType.cni": "Carte Nationale (CNI)",
    "kyc.idType.passport": "Passeport",
    "kyc.idType.permis": "Permis de conduire",
    "kyc.idNumber": "Numéro de pièce",
    "kyc.idNumberPh": "N° de la pièce",
    "kyc.idFront": "Recto de la pièce",
    "kyc.idBack": "Verso de la pièce",
    "kyc.selfie": "Photo portrait (selfie)",
    "kyc.gallery": "Galerie",
    "kyc.galleryHint": "Choisir une photo",
    "kyc.camera": "Caméra",
    "kyc.cameraHint": "Prendre maintenant",
    "kyc.capture": "Capturer",
    "kyc.cancel": "Annuler",
    "kyc.retake": "Reprendre",
    "kyc.replace": "Remplacer",
    "kyc.activateCamera": "Activer la caméra",
    "kyc.selfieHint": "Selfie en direct (sécurité)",
    "kyc.submit": "Soumettre pour vérification",
    "kyc.footerPrivacy": "🔒 Vos données sont chiffrées et utilisées uniquement pour la vérification. Réponse sous 24-48h.",
    "kyc.pending": "KYC soumis — en attente de vérification (24-48h)",
    "kyc.approved": "✓ Fournisseur vérifié — Badge activé",
    "kyc.rejected": "KYC refusé",
    "kyc.rejectReason": "Motif :",
    "kyc.resubmit": "Resoumettre",
    "kyc.submitted": "KYC soumis ! 🎉",
    "kyc.submittedDesc": "Votre demande sera examinée sous 24-48h.",
    "kyc.photoUploaded": "Photo uploadée ✓",
    "kyc.selfieCaptured": "Selfie capturé ✓",
    "kyc.uploadError": "Erreur d'upload",
    "kyc.cameraError": "Impossible d'accéder à la caméra",
    "kyc.errIdNumberRequired": "Remplissez le numéro de pièce",
    "kyc.errFrontRequired": "Veuillez uploader le recto de la pièce",
    "kyc.errSelfieRequired": "Veuillez prendre votre photo (selfie)",
    // Backend / generic errors
    "err.generic": "Une erreur est survenue",
    "err.network": "Problème de connexion. Vérifiez votre réseau.",
    "err.unauthorized": "Vous devez être connecté pour effectuer cette action",
    "err.forbidden": "Action non autorisée",
    "err.notFound": "Ressource introuvable",
    "err.duplicate": "Cet élément existe déjà",
    "err.rateLimit": "Trop de tentatives, réessayez plus tard",
    "err.serverError": "Erreur serveur, réessayez plus tard",
    // Forms
    "form.requiredFields": "Veuillez remplir tous les champs obligatoires",
    "buyer.becomeSellerHint": "Complétez les informations de votre activité pour activer votre compte vendeur.",
    // Chat prefill draft banner
    "chat.prefill.label": "Message prérempli",
    "chat.prefill.hint": "Modifiez ou envoyez pour confirmer",
    "chat.prefill.reset": "Réinitialiser",
    "chat.prefill.discard": "Supprimer le brouillon",
    "chat.prefill.product": "Produit concerné",
  },
  en: {
    "nav.home": "Home",
    "nav.marketplace": "Marketplace",
    "nav.producers": "Network",
    "nav.nukuai": "NUKUCONNECT IA",
    "nav.formations": "Training",
    "nav.traceability": "Traceability",
    "nav.tracking": "Track Order",
    "nav.about": "About",
    "nav.plans": "Plans",
    "nav.categories": "Categories",
    "nav.navigation": "Navigation",
    "nav.langCurrency": "Language & Currency",
    "nav.contact": "Contact",
    "nav.help": "Help Center",
    "auth.login": "Login",
    "auth.signup": "Sign up",
    "auth.logout": "Logout",
    "auth.loginSignup": "Login / Sign up",
    "auth.myAccount": "My account",
    "header.deliverTo": "Deliver to:",
    "header.search": "Search products...",
    "header.searchBtn": "Search",
    "header.notifications": "Notifications",
    "header.readAll": "Read all",
    "header.viewAllNotif": "View all notifications",
    "header.language": "Language",
    "header.currency": "Currency",
    "header.deliveryLocation": "Delivery location",
    "header.currentLocation": "Current location",
    "header.enterAddress": "Enter your address",
    "header.cancel": "Cancel",
    "header.save": "Save",
    "dashboard.title": "Dashboard",
    "dashboard.orders": "My orders",
    "dashboard.payments": "Payments",
    "dashboard.trackOrders": "Track my orders",
    "dashboard.settings": "Settings",
    "cart.title": "My Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptyDesc": "Browse the marketplace to find products",
    "cart.explore": "Explore marketplace",
    "cart.subtotal": "Subtotal",
    "cart.delivery": "Delivery",
    "cart.free": "Free",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "cart.seller": "Seller",
    "cart.back": "Back",
    "cart.articles": "items",
    "cart.deliveryMethod": "Delivery method",
    "cart.deliveryAddress": "Delivery address",
    "cart.city": "City",
    "cart.fullAddress": "Full address",
    "cart.summary": "Summary",
    "cart.addressRequired": "Address required",
    "cart.addressRequiredDesc": "Please enter your delivery address",
    "cart.orderSent": "Order sent!",
    "cart.orderSentDesc": "Your order has been sent to sellers.",
    "cart.sellerContact": "Sellers will contact you to confirm availability and finalize payment",
    "cart.loginRequired": "Login required",
    "cart.loginRequiredDesc": "You must be logged in to place an order",
    "cart.loginBtn": "Log in",
    "mp.searchProduct": "Search a product",
    "mp.productName": "Product name...",
    "mp.allCategories": "All categories",
    "mp.price": "Price",
    "mp.location": "Location",
    "mp.bioOnly": "Organic only",
    "mp.verifiedOnly": "Verified only",
    "mp.reset": "Reset",
    "mp.filters": "Filters",
    "mp.advancedFilters": "Advanced filters",
    "mp.sponsored": "Sponsored Products",
    "mp.viewAll": "View all",
    "mp.products": "products",
    "mp.noProducts": "No products found",
    "mp.noProductsDesc": "Try changing your filters",
    "mp.clear": "Clear",
    "mp.flashDeals": "Flash Deals",
    "mp.forYou": "Selected for you",
    "mp.newArrivals": "New Arrivals",
    "mp.allProducts": "All products",
    "mp.sortRecent": "Most recent",
    "mp.sortPriceAsc": "Price: low to high",
    "mp.sortPriceDesc": "Price: high to low",
    "mp.sortRating": "Top rated",
    "mp.allRegions": "All regions",
    "mp.bio": "Organic",
    "mp.verified": "Verified",
    "mp.productsForSale": "Products for sale",
    "mp.purchaseRequests": "Purchase requests",
    "mp.allPurchaseRequests": "All purchase requests",
    "mp.searchDemand": "Search a request...",
    "mp.allCategoriesFilter": "All categories",
    "mp.recentPublications": "Recent publications",
    "mp.seeAll": "See all →",
    "mp.activeSuppliers": "Active suppliers",
    "mp.seeAllSuppliers": "See all →",
    "product.back": "Back",
    "product.addToCart": "Add to cart",
    "product.addedToCart": "Added to cart",
    "product.contactSeller": "Contact seller",
    "product.sendMessage": "Send a message to",
    "product.send": "Send message",
    "product.messageSent": "Message sent!",
    "product.quantity": "Quantity:",
    "product.estimatedTotal": "Estimated total:",
    "product.available": "available",
    "product.deliveryAvailable": "Delivery available",
    "product.viewProfile": "View profile",
    "product.notFound": "Product not found",
    "product.backToMp": "Back to marketplace",
    "product.traceability": "Product traceability",
    "product.certified": "Certified",
    "product.notCertified": "Not certified",
    "product.contact": "Contact",
    "product.add": "Add",
    "ai.title": "NUKUCONNECT IA",
    "ai.subtitle": "Smart agricultural assistant 24/7",
    "ai.poweredBy": "By NukuConnect AI",
    "ai.placeholder": "Ask your agricultural question...",
    "ai.thinking": "NUKUCONNECT IA is thinking...",
    "ai.suggested": "Suggested questions",
    "ai.categories": "Help categories",
    "ai.cropAdvice": "Crop advice",
    "ai.diseaseId": "Disease identification",
    "ai.marketPrices": "Market prices",
    "ai.seasonal": "Seasonal recommendations",
    "ai.livestock": "Livestock & Cattle",
    "ai.organic": "Organic farming",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Irrigation & Water",
    "hiw.title": "How it works",
    "about.title": "About",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.seeAll": "See all",
    "hero.badge": "Powered by Artificial Intelligence",
    "hero.title1": "Connect your",
    "hero.title2": "agricultural production",
    "hero.title3": "to the world",
    "hero.desc": "NUKUCONNECT revolutionizes agricultural trade in Africa. Sell your products, find reliable buyers and leverage AI to optimize your crops.",
    "hero.cta": "Get started",
    "hero.demo": "Watch demo",
    "hero.stat1": "Producers",
    "hero.stat2": "Purchases made",
    "hero.stat3": "Transactions",
    "sol.delivery": "Fast & traceable delivery",
    "sol.deliveryDesc": "Receive certified agricultural products directly at home with real-time tracking and full traceability guarantee.",
    "sol.deliveryCta": "Order now",
    "sol.markets": "Local & international markets",
    "sol.marketsDesc": "Access a network of producers and buyers across West Africa. Buy and sell securely.",
    "sol.marketsCta": "Explore market",
    "sol.connect": "Pro networking",
    "sol.connectDesc": "Find qualified producers, suppliers, experts and partners to grow your agricultural business.",
    "sol.connectCta": "Become a partner",
    "sol.training": "Specialized training",
    "sol.trainingDesc": "Access training programs in aquaculture, agriculture and agribusiness to boost your skills.",
    "sol.trainingCta": "View training",
    "sol.quickAccess": "Quick access",
    "sol.nukuAI": "Nuku AI",
    "sol.dashboard": "Dashboard",
    "sol.verifiedProducts": "Verified products",
    "home.solutionsBadge": "NUKUCONNECT Solutions",
    "home.solutionsTitleBefore": "Innovative solutions for",
    "home.solutionsTitleHighlight": "your growth",
    "home.solutionsDesc": "A complete platform that connects, trains and boosts agriculture and aquaculture in West Africa and beyond.",
    "home.popularProducts": "Popular products",
    "home.new": "NEW",
    "home.topCategories": "Top Categories",
    "home.productSingular": "product",
    "home.productPlural": "products",
    "home.featuresBadge": "Features",
    "home.featuresTitleBefore": "Everything you need to",
    "home.featuresTitleHighlight": "succeed",
    "home.featuresDesc": "Technology and agriculture to transform your activity.",
    "home.featureMarketplace": "Agricultural Marketplace",
    "home.featureMarketplaceDesc": "Publish and buy agricultural products with ease.",
    "home.featureAssistant": "NUKUCONNECT AI - 24/7 Assistant",
    "home.featureAssistantDesc": "AI chatbot that answers your agricultural questions.",
    "home.featureRecommendations": "AI Recommendations",
    "home.featureRecommendationsDesc": "Suggestions based on your location and preferences.",
    "home.featureTraining": "Agricultural Training",
    "home.featureTrainingDesc": "Online courses and certifications for your techniques.",
    "home.featureTraceability": "Full Traceability",
    "home.featureTraceabilityDesc": "Track your products with QR codes and history.",
    "home.featureNetwork": "Trusted Network",
    "home.featureNetworkDesc": "Ratings and reviews for secure transactions.",
    "home.users": "Users",
    "home.secure": "Secure",
    "home.hiwBadge": "How does it work?",
    "home.hiwTitleBefore": "Buy in",
    "home.hiwTitleHighlight": "4 simple steps",
    "home.hiwDesc": "From account creation to delivery, discover how NUKUCONNECT simplifies agricultural purchases.",
    "home.step1Title": "Create your account",
    "home.step1Desc": "Choose your account type: Producer, Buyer, Supplier, Driver or Learner. Fast and free registration.",
    "home.step1Link": "Sign up",
    "home.step2Title": "Find products & offers",
    "home.step2Desc": "Browse the marketplace, discover local agricultural products and view buyer purchase requests.",
    "home.step2Link": "Explore",
    "home.step3Title": "Place your order",
    "home.step3Desc": "Contact the producer, negotiate and buy securely.",
    "home.step3Link": "Buy",
    "home.step4Title": "Home delivery",
    "home.step4Desc": "Select an available driver near you, track your order in real time and receive fresh products.",
    "home.step4Link": "Track order",
    "home.aiMeet": "Meet",
    "home.aiDesc": "Your intelligent agricultural assistant available 24/7. Ask questions about crops, livestock and plant diseases, and receive personalized advice instantly.",
    "home.aiFeatureAdvice": "Personalized advice 24/7",
    "home.aiFeatureDisease": "Disease diagnosis",
    "home.aiFeatureInstant": "Instant answers",
    "home.aiFeatureLang": "French & local languages",
    "home.aiTry": "Try NUKUCONNECT AI",
    "home.aiOnline": "Online",
    "home.aiPlaceholder": "Ask your question...",
    "home.aiMsgAssistant1": "Hello! I am NUKUCONNECT AI, your agricultural assistant. How can I help you today?",
    "home.aiMsgUser": "How can I improve my tomato yield?",
    "home.aiMsgAssistant2": "To improve your tomatoes:\n\n🌱 Compost-rich soil\n💧 Regular morning watering\n☀️ 6-8h of direct sunlight\n\nWould you like more details?",
    "home.ctaTitleBefore": "Ready to transform your",
    "home.ctaTitleHighlight": "agricultural activity",
    "home.ctaDesc": "Join thousands of producers and buyers who trust NUKUCONNECT to grow their business.",
    "home.ctaCreate": "Create my free account",
    "home.ctaContact": "Contact our team",
    "home.partnersTrust": "Trusted by",
    "home.demandsTitle": "Purchase requests",
    "home.demandsSubtitle": "Buyers are searching — reply directly",
    "home.purchaseBadge": "BUY",
    "home.buyer": "Buyer",
    "home.demandNeed": "Purchase request for",
    "home.moreDemands": "See more requests",
    "home.verifiedSuppliers": "Verified suppliers",
    "home.farmTitleBefore": "Buy directly from",
    "home.farmTitleHighlight": "producers",
    "home.farmTitleAfter": "without intermediaries",
    "home.farmDesc": "Connect with verified suppliers and receive agricultural products directly from the production site. More freshness, fair prices and full traceability.",
    "home.verified100": "100% verified",
    "home.verified100Desc": "Identity & farm checked",
    "home.originGuaranteed": "Guaranteed origin",
    "home.originGuaranteedDesc": "From field to your door",
    "home.nukuDelivery": "Nuku delivery",
    "home.nukuDeliveryDesc": "Internal fleet tracked live",
    "home.buyFromProducers": "Buy from producers",
    "home.viewSuppliers": "View suppliers",
    "home.recentPublications": "Recent publications",
    "home.helpTitle": "Need help?",
    "home.helpDesc": "Chat with our AI Assistant to find what you need.",
    "home.chatNow": "Chat now",
    "home.whatSearch": "What are you looking for?",
    "home.whatSearchDesc": "Describe your question or what you are looking for. NukuConnect AI will answer immediately.",
    "home.helpPlaceholder": "Ex: Which fertilizer for maize?",
    "home.sendToAI": "Send to AI",
    "home.sellTitle": "Sell your products easily",
    "home.sellDesc": "Reach more buyers across Africa.",
    "home.startSelling": "Start selling",
    "home.trustNetworkRealtime": "Trusted network · real time",
    "home.networkTitle": "Nukuconnect Producers & Suppliers",
    "home.viewNetwork": "View network",
    "home.member": "Member",
    "home.verifiedMember": "Verified member",
    "home.aiAssistant": "Agricultural Assistant",
    "home.aiFloatingText": "Ask questions about agriculture, crops, livestock or plant diseases.",
    "home.startConversation": "Start a conversation",
    "net.title": "Our professional network",
    "net.subtitle": "Follow suppliers and buyers to receive their new offers and requests in real time.",
    "net.badge": "NukuConnect Network",
    "net.searchSupplier": "Search a supplier...",
    "net.searchBuyer": "Search a buyer...",
    "net.suppliers": "Suppliers",
    "net.buyers": "Buyers",
    "net.mostRecent": "Most recent",
    "net.bestRated": "Best rated",
    "net.mostProducts": "Most products",
    "net.allCountries": "All countries",
    "net.follow": "Follow",
    "net.following": "Following",
    "net.products": "product",
    "net.productsPlural": "products",
    "net.subscriber": "follower",
    "net.subscribersPlural": "followers",
    "net.buyer": "Buyer",
    "net.verified": "Verified",
    "net.noSupplier": "No supplier found",
    "net.noBuyer": "No buyer found",
    "net.modifyFilters": "Try modifying your search filters.",
    "net.subscribed": "Subscribed!",
    "net.unsubscribed": "Unsubscribed",
    "net.subscribeNotif": "You will receive notifications from",
    "net.unsubscribeNotif": "You no longer follow",
    "footer.platform": "Platform",
    "footer.resources": "Resources",
    "footer.company": "Company",
    "footer.contact": "Contact",
    "footer.terms": "Terms of use",
    "footer.privacy": "Privacy policy",
    "footer.legal": "Legal notices",
    "footer.rights": "All rights reserved.",
    "footer.desc": "The intelligent agricultural marketplace connecting producers and buyers.",
    "footer.downloadApp": "Download the app",
    "footer.downloadDesc": "Access NUKUCONNECT anywhere, anytime.",
    // KYC (supplier)
    "kyc.businessName": "Business / activity name",
    "kyc.businessNamePh": "e.g. Kokoe Farm",
    "kyc.businessType": "Activity type",
    "kyc.businessType.individual": "Individual",
    "kyc.businessType.cooperative": "Cooperative",
    "kyc.businessType.enterprise": "Company",
    "kyc.idType": "ID document type",
    "kyc.idType.cni": "National ID card",
    "kyc.idType.passport": "Passport",
    "kyc.idType.permis": "Driver's license",
    "kyc.idNumber": "ID number",
    "kyc.idNumberPh": "Document number",
    "kyc.idFront": "ID front side",
    "kyc.idBack": "ID back side",
    "kyc.selfie": "Portrait photo (selfie)",
    "kyc.gallery": "Gallery",
    "kyc.galleryHint": "Choose a photo",
    "kyc.camera": "Camera",
    "kyc.cameraHint": "Take now",
    "kyc.capture": "Capture",
    "kyc.cancel": "Cancel",
    "kyc.retake": "Retake",
    "kyc.replace": "Replace",
    "kyc.activateCamera": "Turn on camera",
    "kyc.selfieHint": "Live selfie (security)",
    "kyc.submit": "Submit for verification",
    "kyc.footerPrivacy": "🔒 Your data is encrypted and only used for verification. Reply within 24-48h.",
    "kyc.pending": "KYC submitted — awaiting review (24-48h)",
    "kyc.approved": "✓ Verified supplier — Badge active",
    "kyc.rejected": "KYC rejected",
    "kyc.rejectReason": "Reason:",
    "kyc.resubmit": "Resubmit",
    "kyc.submitted": "KYC submitted! 🎉",
    "kyc.submittedDesc": "Your request will be reviewed within 24-48h.",
    "kyc.photoUploaded": "Photo uploaded ✓",
    "kyc.selfieCaptured": "Selfie captured ✓",
    "kyc.uploadError": "Upload error",
    "kyc.cameraError": "Cannot access camera",
    "kyc.errIdNumberRequired": "Please enter the ID number",
    "kyc.errFrontRequired": "Please upload the ID front side",
    "kyc.errSelfieRequired": "Please take your selfie photo",
    // Backend / generic errors
    "err.generic": "Something went wrong",
    "err.network": "Connection issue. Check your network.",
    "err.unauthorized": "You must be signed in to do that",
    "err.forbidden": "Action not allowed",
    "err.notFound": "Resource not found",
    "err.duplicate": "This item already exists",
    "err.rateLimit": "Too many attempts, try again later",
    "err.serverError": "Server error, try again later",
    "form.requiredFields": "Please fill in all required fields",
    "buyer.becomeSellerHint": "Complete your business information to activate your seller account.",
    "chat.prefill.label": "Prefilled message",
    "chat.prefill.hint": "Edit or send to confirm",
    "chat.prefill.reset": "Reset",
    "chat.prefill.discard": "Discard draft",
    "chat.prefill.product": "Related product",
  },
  ewe: {
    "nav.home": "Aƒe",
    "nav.marketplace": "Asitsaƒe",
    "nav.producers": "Hã",
    "nav.nukuai": "NUKUCONNECT IA",
    "nav.formations": "Kpɔɖeŋu",
    "nav.traceability": "Nudi dzadzɛ",
    "nav.tracking": "Dze nuɖoɖo ƒe ŋkume",
    "nav.about": "Ŋuti nyawo",
    "nav.plans": "Fexexe ƒe dzesi",
    "nav.categories": "Hatsatsa",
    "nav.navigation": "Mɔɖoɖo",
    "nav.langCurrency": "Gbe kple ga",
    "nav.contact": "Kaɖoɖo",
    "nav.help": "Kpekpeɖeŋu",
    "auth.login": "Ge ɖe eme",
    "auth.signup": "Ŋlɔ ŋkɔ",
    "auth.logout": "Tso ɖe go",
    "auth.loginSignup": "Ge ɖe eme / Ŋlɔ ŋkɔ",
    "auth.myAccount": "Nye ŋkɔnta",
    "header.deliverTo": "Na ɖo ɖe:",
    "header.search": "Di nu aɖe...",
    "header.searchBtn": "Di",
    "header.notifications": "Nyagbɔgblɔwo",
    "header.readAll": "Xlẽ wokatã",
    "header.viewAllNotif": "Kpɔ nyagbɔgblɔ wokatã",
    "header.language": "Gbe",
    "header.currency": "Ga",
    "header.deliveryLocation": "Nuɖoɖo ƒe teƒe",
    "header.currentLocation": "Teƒe si li fifia",
    "header.enterAddress": "De wò adrese",
    "header.cancel": "Dzudzɔ",
    "header.save": "Dzra ɖi",
    "dashboard.title": "Dɔwɔƒe",
    "dashboard.orders": "Nye ɖoɖowo",
    "dashboard.payments": "Fexexe",
    "dashboard.trackOrders": "Dze nye ɖoɖo ƒe ŋkume",
    "dashboard.settings": "Ɖoɖo",
    "cart.title": "Nye agba",
    "cart.empty": "Wò agba le ƒuƒlu",
    "cart.emptyDesc": "Kpɔ asitsaƒe la dzi be nàdi nuwo",
    "cart.explore": "Kpɔ asitsaƒe",
    "cart.subtotal": "Akɔnta eve",
    "cart.delivery": "Nuɖoɖo",
    "cart.free": "Fiafia",
    "cart.total": "Katã",
    "cart.checkout": "Ɖo ɖoɖo",
    "cart.seller": "Nudzrala",
    "cart.back": "Trɔ yi",
    "cart.articles": "nuwo",
    "cart.deliveryMethod": "Nuɖoɖo ƒe mɔnu",
    "cart.deliveryAddress": "Nuɖoɖo ƒe adrese",
    "cart.city": "Du",
    "cart.fullAddress": "Adrese blibo",
    "cart.summary": "Gɔmedzese",
    "cart.addressRequired": "Adrese hiã",
    "cart.addressRequiredDesc": "Taflatse ŋlɔ wò nuɖoɖo ƒe adrese",
    "cart.orderSent": "Woɖo ɖoɖo!",
    "cart.orderSentDesc": "Woɖo wò ɖoɖo na nudzralawo.",
    "cart.sellerContact": "Nudzralawo aɖo ka ɖe wò gbɔ",
    "cart.loginRequired": "Gege ɖe eme hiã",
    "cart.loginRequiredDesc": "Ele be nàge ɖe eme hafi nàɖo ɖoɖo",
    "cart.loginBtn": "Ge ɖe eme",
    "mp.searchProduct": "Di nunu aɖe",
    "mp.productName": "Nunu ƒe ŋkɔ...",
    "mp.allCategories": "Hatsatsa wokatã",
    "mp.price": "Asixɔxɔ",
    "mp.location": "Teƒe",
    "mp.bioOnly": "Bio ko",
    "mp.verifiedOnly": "Wokpɔe ɖe edzi ko",
    "mp.reset": "Trɔ ɖe dzi",
    "mp.filters": "Titia",
    "mp.advancedFilters": "Titia si dze edzi",
    "mp.sponsored": "Nuwo si woɖo ga na",
    "mp.viewAll": "Kpɔ katã",
    "mp.products": "nuwo",
    "mp.noProducts": "Womekpɔ nu aɖeke o",
    "mp.noProductsDesc": "Tsi titia bubuwo kpɔ",
    "mp.clear": "Tutu",
    "mp.flashDeals": "Asitsatsa ŋkɔŋkɔ",
    "mp.forYou": "Wotia na wò",
    "mp.newArrivals": "Nuwo si va yeye",
    "mp.allProducts": "Nuwo katã",
    "mp.sortRecent": "Yeyewo gbã",
    "mp.sortPriceAsc": "Asixɔxɔ: ɖoɖoe va gã",
    "mp.sortPriceDesc": "Asixɔxɔ: gã va ɖoɖoe",
    "mp.sortRating": "Nyuiewo gbã",
    "mp.allRegions": "Nutome wokatã",
    "mp.bio": "Bio",
    "mp.verified": "Wokpɔe ɖe edzi",
    "mp.productsForSale": "Nuwo si woɖe dzra ge",
    "mp.purchaseRequests": "Nuƒleƒle biabiawo",
    "mp.allPurchaseRequests": "Nuƒleƒle biabiawo katã",
    "mp.searchDemand": "Di biabia aɖe...",
    "mp.allCategoriesFilter": "Hatsatsa wokatã",
    "mp.recentPublications": "Yeyewo si va",
    "mp.seeAll": "Kpɔ katã →",
    "mp.activeSuppliers": "Nudzralawo si le dɔ wɔm",
    "mp.seeAllSuppliers": "Kpɔ wokatã →",
    "product.back": "Trɔ yi",
    "product.addToCart": "De agba me",
    "product.addedToCart": "Wode agba me",
    "product.contactSeller": "Ka ɖo nudzrala",
    "product.sendMessage": "Dɔ ŋutinya na",
    "product.send": "Dɔ ŋutinya",
    "product.messageSent": "Woɖo ŋutinya!",
    "product.quantity": "Gbɔsɔsɔ:",
    "product.estimatedTotal": "Katã si wobu:",
    "product.available": "woliwo",
    "product.deliveryAvailable": "Nuɖoɖo li",
    "product.viewProfile": "Kpɔ ŋkɔnta",
    "product.notFound": "Womekpɔ nu la o",
    "product.backToMp": "Trɔ yi asitsaƒe",
    "product.traceability": "Nunu ƒe dzadzɛ",
    "product.certified": "Wodzɛe",
    "product.notCertified": "Womedzɛe o",
    "product.contact": "Ka ɖo",
    "product.add": "De eme",
    "ai.title": "NUKUCONNECT IA",
    "ai.subtitle": "Agble ŋutinya na ŋkeke 24/7",
    "ai.poweredBy": "Tso NukuConnect IA",
    "ai.placeholder": "Bia wò agble biabia...",
    "ai.thinking": "NUKUCONNECT IA le susu ɖom...",
    "ai.suggested": "Biabiawo si wotia",
    "ai.categories": "Kpekpeɖeŋu ƒe hatsatsa",
    "ai.cropAdvice": "Agble dɔwɔwɔ ƒe aɖaŋu",
    "ai.diseaseId": "Dɔlele ƒe dzadzɛ",
    "ai.marketPrices": "Asitsaƒe asixɔxɔwo",
    "ai.seasonal": "Ɣeyiɣi ƒe aɖaŋu",
    "ai.livestock": "Lãwo",
    "ai.organic": "Bio agbledede",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Tsi kple tɔ̃me",
    "hiw.title": "Alesi ewɔna",
    "about.title": "Ŋuti nyawo",
    "common.loading": "Le dzadzram...",
    "common.error": "Vodada",
    "common.seeAll": "Kpɔ katã",
    "hero.badge": "Nuŋɔŋlɔ ŋutsu le edzi",
    "hero.title1": "Ka wò",
    "hero.title2": "agble dɔwɔwɔ",
    "hero.title3": "ɖo xexeame katã",
    "hero.desc": "NUKUCONNECT trɔ agble asitsatsa le Afrika. Dzra wò nuwo, di nuƒlelawo kple IA ƒe kpekpeɖeŋu.",
    "hero.cta": "Dze egɔme fifia",
    "hero.demo": "Kpɔ demo la",
    "hero.stat1": "Nudzralawo",
    "hero.stat2": "Nuƒleƒle wowɔwo",
    "hero.stat3": "Asitsatsa",
    "sol.delivery": "Nuɖoɖo kabakaba kple dzadzɛ",
    "sol.deliveryDesc": "Xɔ agble nuwo si wodzɛ ɖe wò aƒe kpɔ̃ kple ŋkume dzedzem.",
    "sol.deliveryCta": "Ɖo ɖoɖo fifia",
    "sol.markets": "Teƒe kple xexeame asitsaƒewo",
    "sol.marketsDesc": "Ge ɖe nudzralawo kple nuƒlelawo hã me le Afrika Ɣedzeƒe.",
    "sol.marketsCta": "Kpɔ asitsaƒe la",
    "sol.connect": "Pro kpɔɖeŋu",
    "sol.connectDesc": "Di nudzralawo, kpekpeɖeŋu viwo kple hãmegãwo.",
    "sol.connectCta": "Zu hãmegã",
    "sol.training": "Kpɔɖeŋu tiatia",
    "sol.trainingDesc": "Ge ɖe tɔmedede, agbledede kple agribusiness kpɔɖeŋu me.",
    "sol.trainingCta": "Kpɔ kpɔɖeŋuwo",
    "sol.quickAccess": "Mɔɖoɖo kabakaba",
    "sol.nukuAI": "Nuku IA",
    "sol.dashboard": "Dɔwɔƒe",
    "sol.verifiedProducts": "Nuwo si wodzɛ",
    "net.title": "Míaƒe hã dɔwɔƒe",
    "net.subtitle": "Dze nudzralawo kple nuƒlelawo ŋkume be nàxɔ woƒe nuwo kple biabiawo yeyewo.",
    "net.badge": "NukuConnect Hã",
    "net.searchSupplier": "Di nudzrala aɖe...",
    "net.searchBuyer": "Di nuƒlela aɖe...",
    "net.suppliers": "Nudzralawo",
    "net.buyers": "Nuƒlelawo",
    "net.mostRecent": "Yeyewo gbã",
    "net.bestRated": "Nyuiewo gbã",
    "net.mostProducts": "Nuwo gbɔsɔsɔ",
    "net.allCountries": "Dukɔ wokatã",
    "net.follow": "Dze ŋkume",
    "net.following": "Le ŋkume dzem",
    "net.products": "nunu",
    "net.productsPlural": "nuwo",
    "net.subscriber": "ŋkumedzelaa",
    "net.subscribersPlural": "ŋkumedzelawo",
    "net.buyer": "Nuƒlela",
    "net.verified": "Wokpɔe ɖe edzi",
    "net.noSupplier": "Womekpɔ nudzrala aɖeke o",
    "net.noBuyer": "Womekpɔ nuƒlela aɖeke o",
    "net.modifyFilters": "Trɔ wò titia kpɔ.",
    "net.subscribed": "Wode ŋkɔ!",
    "net.unsubscribed": "Wotso",
    "net.subscribeNotif": "Nàxɔ nyagbɔgblɔ tso",
    "net.unsubscribeNotif": "Mele ŋkume dzem na",
    "footer.platform": "Asitsaƒe",
    "footer.resources": "Nuwo",
    "footer.company": "Dɔwɔƒe",
    "footer.contact": "Kaɖoɖo",
    "footer.terms": "Zãɖoɖo ƒe se",
    "footer.privacy": "Nyatakakawo ƒe se",
    "footer.legal": "Sewo ŋuti nyawo",
    "footer.rights": "Mɔɖoɖo katã dzɛ ɖe asi.",
    "footer.desc": "Agble asitsaƒe nyui si ka nudzralawo kple nuƒlelawo ɖo.",
    "footer.downloadApp": "Ɖa app la ɖi",
    "footer.downloadDesc": "Ge ɖe NUKUCONNECT me ɖe teƒe sia teƒe.",
  },
  kab: {
    "nav.home": "Ɖɩsɩ",
    "nav.marketplace": "Kɩyakʊ",
    "nav.producers": "Kpɛndɩnaa",
    "nav.nukuai": "NUKUCONNECT IA",
    "nav.formations": "Kpɛlɩkʊ",
    "nav.traceability": "Ñɩnɩʊ",
    "nav.tracking": "Ðɔɖɔ ñɩnɩʊ",
    "nav.about": "Tɔm taa",
    "nav.plans": "Liidiye",
    "nav.categories": "Hɔɔlʊʊ",
    "nav.navigation": "Nʊmɔʊ",
    "nav.langCurrency": "Kʊnʊŋ kple liidiye",
    "nav.contact": "Yɔɔdɩ",
    "nav.help": "Sɩnʊʊ",
    "auth.login": "Sʊʊ",
    "auth.signup": "Maʊ hɩɖɛ",
    "auth.logout": "Lɩɩ",
    "auth.loginSignup": "Sʊʊ / Maʊ hɩɖɛ",
    "auth.myAccount": "Ma-tɩŋ",
    "header.deliverTo": "Pɩsɩ:",
    "header.search": "Ñɩnɩ...",
    "header.searchBtn": "Ñɩnɩ",
    "header.notifications": "Tɔm kɩfam",
    "header.readAll": "Kalɩ tɩŋa",
    "header.viewAllNotif": "Na tɔm kɩfam tɩŋa",
    "header.language": "Kʊnʊŋ",
    "header.currency": "Liidiye",
    "header.deliveryLocation": "Pɩsɩʊ lone",
    "header.currentLocation": "Lone lɛɛlɛɛ",
    "header.enterAddress": "Ma wɛ adrese",
    "header.cancel": "Kizi",
    "header.save": "Ðɔkɩ",
    "dashboard.title": "Tɔm taa",
    "dashboard.orders": "Ma ɖɔɖɔ",
    "dashboard.payments": "Hɛyʊʊ",
    "dashboard.trackOrders": "Ðɔɖɔ ñɩnɩʊ",
    "dashboard.settings": "Lɩmaɣzɩ",
    "cart.title": "Ma huyuu",
    "cart.empty": "Wɛ huyuu fɛyɩ",
    "cart.emptyDesc": "Wolo kɩyakʊ taa se ñɩnɩ wondu",
    "cart.explore": "Na kɩyakʊ",
    "cart.subtotal": "Tɩŋa lɛɛ",
    "cart.delivery": "Pɩsɩʊ",
    "cart.free": "Falaa",
    "cart.total": "Tɩŋa",
    "cart.checkout": "Ðɔɖɔ",
    "cart.seller": "Pɛdɩyaa",
    "cart.back": "Pɩsɩ",
    "cart.articles": "wondu",
    "cart.deliveryMethod": "Pɩsɩʊ nʊmɔʊ",
    "cart.deliveryAddress": "Pɩsɩʊ adrese",
    "cart.city": "Tɛtʊ",
    "cart.fullAddress": "Adrese tɩŋa",
    "cart.summary": "Tɔm kpɛlɩkʊ",
    "cart.addressRequired": "Adrese tɔm",
    "cart.addressRequiredDesc": "Ma wɛ adrese",
    "cart.orderSent": "Patɩ ɖɔɖɔ!",
    "cart.orderSentDesc": "Paɖɩ wɛ ɖɔɖɔ.",
    "cart.sellerContact": "Pɛdɩyaa kaɣ-ŋ yɔɔdɩnʊʊ",
    "cart.loginRequired": "Pɩwɛɛ se sʊʊ",
    "cart.loginRequiredDesc": "Pɩwɛɛ se sʊʊ nɛ pʊcɔ ɖɔɖɔ",
    "cart.loginBtn": "Sʊʊ",
    "mp.searchProduct": "Ñɩnɩ pʊyʊ",
    "mp.productName": "Pʊyʊ hɩɖɛ...",
    "mp.allCategories": "Hɔɔlʊʊ tɩŋa",
    "mp.price": "Liidiye",
    "mp.location": "Lone",
    "mp.bioOnly": "Bio ɖeke",
    "mp.verifiedOnly": "Pawɩlɩ ɖeke",
    "mp.reset": "Pɩsɩ kiɖe",
    "mp.filters": "Titia",
    "mp.advancedFilters": "Titia kɩfasɩ",
    "mp.sponsored": "Wondu ɖɩfɛyɩ",
    "mp.viewAll": "Na tɩŋa",
    "mp.products": "wondu",
    "mp.noProducts": "Patɩlɩɣ pʊyʊ",
    "mp.noProductsDesc": "Lɛɣzɩ titia",
    "mp.clear": "Hɩzɩ",
    "mp.flashDeals": "Kɩyakʊ lɛɛ",
    "mp.forYou": "Ña-tɩŋ",
    "mp.newArrivals": "Kɩfasɩ",
    "mp.allProducts": "Wondu tɩŋa",
    "mp.sortRecent": "Kɩfasɩ",
    "mp.sortPriceAsc": "Liidiye: cikpem",
    "mp.sortPriceDesc": "Liidiye: sɔsɔm",
    "mp.sortRating": "Kɩlɩm",
    "mp.allRegions": "Egeetiye tɩŋa",
    "mp.bio": "Bio",
    "mp.verified": "Pawɩlɩ",
    "mp.productsForSale": "Wondu ɖɩtɛ",
    "mp.purchaseRequests": "Ðɔɖɔ pɔzɩ",
    "mp.allPurchaseRequests": "Ðɔɖɔ pɔzɩ tɩŋa",
    "mp.searchDemand": "Ñɩnɩ pɔzɩ...",
    "mp.allCategoriesFilter": "Hɔɔlʊʊ tɩŋa",
    "mp.recentPublications": "Kɩfasɩ",
    "mp.seeAll": "Na tɩŋa →",
    "mp.activeSuppliers": "Pɛdɩyaa mba pɛwɛɛ",
    "mp.seeAllSuppliers": "Na tɩŋa →",
    "product.back": "Pɩsɩ",
    "product.addToCart": "Sɩɩ huyuu taa",
    "product.addedToCart": "Pasɩ huyuu taa",
    "product.contactSeller": "Yɔɔdɩnɩ pɛdɩyaa",
    "product.sendMessage": "Tɩyɩ tɔm",
    "product.send": "Tɩyɩ tɔm",
    "product.messageSent": "Patɩyɩ tɔm!",
    "product.quantity": "Ɖɔɖɔ:",
    "product.estimatedTotal": "Tɩŋa:",
    "product.available": "wɛɛ",
    "product.deliveryAvailable": "Pɩsɩʊ wɛɛ",
    "product.viewProfile": "Na tɔm",
    "product.notFound": "Patɩlɩɣ pʊyʊ",
    "product.backToMp": "Pɩsɩ kɩyakʊ",
    "product.traceability": "Pʊyʊ ñɩnɩʊ",
    "product.certified": "Pawɩlɩ",
    "product.notCertified": "Patɩwɩlɩ",
    "product.contact": "Yɔɔdɩ",
    "product.add": "Sɩɩ",
    "ai.title": "NUKUCONNECT IA",
    "ai.subtitle": "Hayɩm sɩnɩyʊ 24/7",
    "ai.poweredBy": "NukuConnect IA",
    "ai.placeholder": "Pɔzɩ wɛ tɔm...",
    "ai.thinking": "NUKUCONNECT IA maɣzɩɣ...",
    "ai.suggested": "Tɔm ndʊ pɔzɩ",
    "ai.categories": "Sɩnʊʊ hɔɔlʊʊ",
    "ai.cropAdvice": "Hayɩm lɔŋ",
    "ai.diseaseId": "Kʊdɔŋ ñɩnɩʊ",
    "ai.marketPrices": "Kɩyakʊ liidiye",
    "ai.seasonal": "Alɩwaatʊ lɔŋ",
    "ai.livestock": "Kpɩna",
    "ai.organic": "Bio hayɩm",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Lɩm",
    "hiw.title": "Ɛzɩma pɩlakɩ",
    "about.title": "Tɔm taa",
    "common.loading": "Ðɩɖaŋ...",
    "common.error": "Pɩtɛkɛdɩ",
    "common.seeAll": "Na tɩŋa",
    "hero.badge": "Lɛɣtʊ sɩŋɩ",
    "hero.title1": "Tʊmɩyɛ ñɛ",
    "hero.title2": "hayɩm tʊmɩyɛ",
    "hero.title3": "ɛjaɖɛ kpeekpe",
    "hero.desc": "NUKUCONNECT lɛɣzɩ hayɩm kɩyakʊ Afrika taa. Pɛdɩ wɛ wondu, ñɩnɩ ɖɔɖɔyaa nɛ IA sɩnɩ-ŋ.",
    "hero.cta": "Paɣzɩ lɛɛlɛɛ",
    "hero.demo": "Na demo",
    "hero.stat1": "Pɛdɩyaa",
    "hero.stat2": "Ðɔɖɔ wɔɔ",
    "hero.stat3": "Kɩyakʊ",
    "net.title": "Ɖa hã taa",
    "net.subtitle": "Dze pɛdɩyaa kple ɖɔɖɔyaa ŋkume nɛ nàna wondu kɩfasɩ.",
    "net.badge": "NukuConnect Hã",
    "net.searchSupplier": "Ñɩnɩ pɛdɩyaa...",
    "net.searchBuyer": "Ñɩnɩ ɖɔɖɔyaa...",
    "net.suppliers": "Pɛdɩyaa",
    "net.buyers": "Ðɔɖɔyaa",
    "net.mostRecent": "Kɩfasɩ",
    "net.bestRated": "Kɩlɩm",
    "net.mostProducts": "Wondu sakɩyɛ",
    "net.allCountries": "Ajɛya tɩŋa",
    "net.follow": "Ðɔ",
    "net.following": "Ðɔm",
    "net.products": "pʊyʊ",
    "net.productsPlural": "wondu",
    "net.subscriber": "ɖɔyʊ",
    "net.subscribersPlural": "ɖɔyaa",
    "net.buyer": "Ðɔɖɔyʊ",
    "net.verified": "Pawɩlɩ",
    "net.noSupplier": "Patɩlɩɣ pɛdɩyaa",
    "net.noBuyer": "Patɩlɩɣ ɖɔɖɔyʊ",
    "net.modifyFilters": "Lɛɣzɩ titia.",
    "net.subscribed": "Paɖɔ!",
    "net.unsubscribed": "Patɩɖɔ",
    "net.subscribeNotif": "Ŋkaɣ na tɔm tso",
    "net.unsubscribeNotif": "Ŋtɩɖɔɔ",
    "footer.platform": "Kɩyakʊ",
    "footer.resources": "Wondu",
    "footer.company": "Tʊmɩyɛ",
    "footer.contact": "Yɔɔdɩ",
    "footer.terms": "Labɩnʊʊ se",
    "footer.privacy": "Mɛsaɣ se",
    "footer.legal": "Paɣtʊ se",
    "footer.rights": "Waɣ tɩŋa.",
    "footer.desc": "Hayɩm kɩyakʊ sɩŋɩ.",
    "footer.downloadApp": "Kpaɣ app",
    "footer.downloadDesc": "Sʊʊ NUKUCONNECT paa.",
  },
  wo: {
    "nav.home": "Kër",
    "nav.marketplace": "Marse",
    "nav.producers": "Réseau",
    "nav.nukuai": "NUKUCONNECT IA",
    "nav.formations": "Jàng",
    "nav.traceability": "Wërusit",
    "nav.tracking": "Toppoo yóbbu",
    "nav.about": "Ci xam-xam",
    "nav.plans": "Wàll",
    "nav.categories": "Xeet",
    "nav.navigation": "Yoon",
    "nav.langCurrency": "Làkk ak xaalis",
    "nav.contact": "Jokkoo",
    "nav.help": "Ndimbal",
    "auth.login": "Dugg",
    "auth.signup": "Bindu",
    "auth.logout": "Génne",
    "auth.loginSignup": "Dugg / Bindu",
    "auth.myAccount": "Sama kont",
    "header.deliverTo": "Yóbbu ci:",
    "header.search": "Wut...",
    "header.searchBtn": "Wut",
    "header.notifications": "Xëbar yi",
    "header.readAll": "Jàng lépp",
    "header.viewAllNotif": "Xool xëbar yépp",
    "header.language": "Làkk",
    "header.currency": "Xaalis",
    "header.deliveryLocation": "Bërëb yóbbu",
    "header.currentLocation": "Bërëb bi léegi",
    "header.enterAddress": "Dugal sa adres",
    "header.cancel": "Bàyyi",
    "header.save": "Denc",
    "dashboard.title": "Tablo",
    "dashboard.orders": "Sama commande yi",
    "dashboard.payments": "Fay",
    "dashboard.trackOrders": "Toppoo sama commande",
    "dashboard.settings": "Parameetar",
    "cart.title": "Sama panier",
    "cart.empty": "Sa panier amul dara",
    "cart.emptyDesc": "Xoolal marse bi ngir wut jën",
    "cart.explore": "Xool marse bi",
    "cart.subtotal": "Bokk",
    "cart.delivery": "Yóbbu",
    "cart.free": "Fay-fayul",
    "cart.total": "Tollu",
    "cart.checkout": "Commande",
    "cart.seller": "Jëndëkaat",
    "cart.back": "Dellu",
    "cart.articles": "yenn",
    "cart.deliveryMethod": "Yoon wu yóbbu",
    "cart.deliveryAddress": "Adres bu yóbbu",
    "cart.city": "Dëkk",
    "cart.fullAddress": "Adres bu mat",
    "cart.summary": "Tektal",
    "cart.addressRequired": "Adres laaj na",
    "cart.addressRequiredDesc": "Dugalal sa adres bu yóbbu",
    "cart.orderSent": "Commande gi yónnee na!",
    "cart.orderSentDesc": "Sa commande gi yónnee na ci jëndëkaat yi.",
    "cart.sellerContact": "Jëndëkaat yi dinañu la woo",
    "cart.loginRequired": "Wànte dugg",
    "cart.loginRequiredDesc": "Wànte dugg ngir def commande",
    "cart.loginBtn": "Dugg",
    "mp.searchProduct": "Wut jën",
    "mp.productName": "Tur jën...",
    "mp.allCategories": "Xeet yépp",
    "mp.price": "Njëg",
    "mp.location": "Bërëb",
    "mp.bioOnly": "Bio rekk",
    "mp.verifiedOnly": "Yu wërul rekk",
    "mp.reset": "Dellu",
    "mp.filters": "Sàcc",
    "mp.advancedFilters": "Sàcc bu yëg",
    "mp.sponsored": "Jën yu sponsor",
    "mp.viewAll": "Xool lépp",
    "mp.products": "jën",
    "mp.noProducts": "Amul jën",
    "mp.noProductsDesc": "Jéemël weccil sàcc",
    "mp.clear": "Sopp",
    "mp.flashDeals": "Offre gaaw",
    "mp.forYou": "Ngir yow",
    "mp.newArrivals": "Yu bees",
    "mp.allProducts": "Jën yépp",
    "mp.sortRecent": "Yu mujj",
    "mp.sortPriceAsc": "Njëg: ndaw ba mag",
    "mp.sortPriceDesc": "Njëg: mag ba ndaw",
    "mp.sortRating": "Yu gëna baax",
    "mp.allRegions": "Bërëb yépp",
    "mp.bio": "Bio",
    "mp.verified": "Wërul",
    "mp.productsForSale": "Jën yu jënd",
    "mp.purchaseRequests": "Laaj jënd",
    "mp.allPurchaseRequests": "Laaj jënd yépp",
    "mp.searchDemand": "Wut laaj...",
    "mp.allCategoriesFilter": "Xeet yépp",
    "mp.recentPublications": "Yu bees",
    "mp.seeAll": "Xool lépp →",
    "mp.activeSuppliers": "Jëndëkaat yu bees",
    "mp.seeAllSuppliers": "Xool lépp →",
    "product.back": "Dellu",
    "product.addToCart": "Dugal ci panier",
    "product.addedToCart": "Dugal na ci panier",
    "product.contactSeller": "Jokkoo ak jëndëkaat",
    "product.sendMessage": "Yónne bataaxal ci",
    "product.send": "Yónne",
    "product.messageSent": "Bataaxal bi yónnee na!",
    "product.quantity": "Yàgg:",
    "product.estimatedTotal": "Tollu:",
    "product.available": "am nañu",
    "product.deliveryAvailable": "Yóbbu am na",
    "product.viewProfile": "Xool profil",
    "product.notFound": "Gisul jën",
    "product.backToMp": "Dellu marse",
    "product.traceability": "Wërusit bu jën",
    "product.certified": "Certificat",
    "product.notCertified": "Amul certificat",
    "product.contact": "Jokkoo",
    "product.add": "Dugal",
    "ai.title": "NUKUCONNECT IA",
    "ai.subtitle": "Ndimbal bu tool ci agrokultur 24/7",
    "ai.poweredBy": "NukuConnect IA",
    "ai.placeholder": "Laajal sa laaj ci tool...",
    "ai.thinking": "NUKUCONNECT IA di xalaat...",
    "ai.suggested": "Laaj yu ñu tànn",
    "ai.categories": "Xeet ndimbal",
    "ai.cropAdvice": "Digal ci tool",
    "ai.diseaseId": "Feebar ñibbi",
    "ai.marketPrices": "Njëg ci marse",
    "ai.seasonal": "Digal ci weer",
    "ai.livestock": "Mala",
    "ai.organic": "Tool bio",
    "ai.business": "Agribusiness",
    "ai.irrigation": "Ndox",
    "hiw.title": "Nan la doxe",
    "about.title": "Ci xam-xam",
    "common.loading": "Ngi yéeg...",
    "common.error": "Njuumte",
    "common.seeAll": "Xool lépp",
    "hero.badge": "Ak xel bu pexe",
    "hero.title1": "Tëgal sa",
    "hero.title2": "liggéey ci tool",
    "hero.title3": "ci àdduna bi",
    "hero.desc": "NUKUCONNECT dina weccil jënd ci tool ci Afrig. Jëndal sa jën, wutal jëndëkaat yu baax te jëflante ak IA.",
    "hero.cta": "Tàmbalee léegi",
    "hero.demo": "Xool demo",
    "hero.stat1": "Jëndëkaat",
    "hero.stat2": "Jënd yu defoon",
    "hero.stat3": "Transaction",
    "net.title": "Sunu réseau professionnel",
    "net.subtitle": "Toppoo jëndëkaat ak jëndëkaat ngir am xëbar yu bees.",
    "net.badge": "Réseau NukuConnect",
    "net.searchSupplier": "Wut jëndëkaat...",
    "net.searchBuyer": "Wut jëndëkaat...",
    "net.suppliers": "Jëndëkaat",
    "net.buyers": "Jëndëkaat",
    "net.mostRecent": "Yu mujj",
    "net.bestRated": "Yu gëna baax",
    "net.mostProducts": "Jën bu bari",
    "net.allCountries": "Réew yépp",
    "net.follow": "Toppoo",
    "net.following": "Ngi toppoo",
    "net.products": "jën",
    "net.productsPlural": "jën",
    "net.subscriber": "toppatoo",
    "net.subscribersPlural": "toppatoo",
    "net.buyer": "Jëndëkaat",
    "net.verified": "Wërul",
    "net.noSupplier": "Amul jëndëkaat",
    "net.noBuyer": "Amul jëndëkaat",
    "net.modifyFilters": "Weccil sàcc.",
    "net.subscribed": "Toppoo na!",
    "net.unsubscribed": "Bàyyi na",
    "net.subscribeNotif": "Dinaa am xëbar bu",
    "net.unsubscribeNotif": "Toppatul",
    "footer.platform": "Plateforme",
    "footer.resources": "Ressources",
    "footer.company": "Entreprise",
    "footer.contact": "Jokkoo",
    "footer.terms": "Màndarga",
    "footer.privacy": "Sutura",
    "footer.legal": "Yoon",
    "footer.rights": "Sañ-sañ yépp.",
    "footer.desc": "Marse bu xel ci tool bu tëgal jëndëkaat ak jëndëkaat.",
    "footer.downloadApp": "Jël app bi",
    "footer.downloadDesc": "Dugg ci NUKUCONNECT fenn, fànn.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const SUPPORTED_LANGS: LangCode[] = ["fr", "en", "ewe", "kab", "wo"];

const detectBrowserLang = (): LangCode => {
  if (typeof navigator === "undefined") return "fr";
  const candidates: string[] = [];
  if (navigator.languages && navigator.languages.length) candidates.push(...navigator.languages);
  if (navigator.language) candidates.push(navigator.language);
  for (const raw of candidates) {
    const code = raw.toLowerCase().split("-")[0];
    if (code === "fr") return "fr";
    if (code === "en") return "en";
    if (code === "ee" || code === "ewe") return "ewe";
    if (code === "kab" || code === "ber") return "kab";
    if (code === "wo") return "wo";
  }
  return "en"; // default for non-French browsers instead of forcing FR
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<LangCode>(() => {
    const stored = localStorage.getItem("nukuconnect-lang") as LangCode | null;
    if (stored && SUPPORTED_LANGS.includes(stored)) return stored;
    return detectBrowserLang();
  });
  const [currency, setCurrency] = useState<CurrencyCode>(() => {
    return (localStorage.getItem("nukuconnect-currency") as CurrencyCode) || "XOF";
  });

  useEffect(() => {
    localStorage.setItem("nukuconnect-lang", lang);
  }, [lang]);

  useEffect(() => {
    localStorage.setItem("nukuconnect-currency", currency);
  }, [currency]);

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations.fr[key] || key;
  };

  const formatPrice = (priceXOF: number): string => {
    const converted = priceXOF * exchangeRates[currency];
    const symbol = currencySymbols[currency];
    if (currency === "XOF") {
      // Use en-US so the thousand separator is a visible comma (e.g. "15,229 F CFA")
      return `${new Intl.NumberFormat("en-US").format(Math.round(converted))} ${symbol}`;
    }
    return `${symbol}${new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(converted)}`;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, currency, setCurrency, t, formatPrice }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
